# Custom settings for the skims data, helping to define the skims variables and impedence levels
"06197001":
  skims:
    beam: {columns: ['SOV_AM_IVT_mins'],
        impedance_names: {'SOV_AM_IVT_mins': 'sov'},
        impedance_units: 'min',
        impedance_thresholds: [5, 10, 15, 20, 25, 30],
        zones_table: 'zones'}
"48197301":
  skims:
    beam: {columns: ['SOV_AM_IVT_mins'],
        impedance_names: {'SOV_AM_IVT_mins': 'sov_c'},
        impedance_units: 'min',
        impedance_thresholds: [5, 10, 15, 20, 25, 30],
        zones_table: 'zones'}
    polaris: {columns: ['auto_ivtt_8_9_am', 'auto_cost_8_9_am'],
        impedance_names: {'auto_ivtt_8_9_am': 'sov_t', 'auto_cost_8_9_am': 'sov_c'},
        impedance_units: 'min',
        impedance_thresholds: [5, 10, 15, 20, 25, 30],
        zones_table: 'zones'}