modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.7838205099105835
  - -1.7523012161254883
  - -0.21840554475784302
  - 0.2985743582248688
  - 1.1451551914215088
  - -2.34505558013916
  - -0.0033771477174013853
  - -0.5043216943740845
  - -0.6832804679870605
  - -0.11167912930250168
  - -3.6435906887054443
  - 0.00045005977153778076
  - 3.5715503692626953
  - 1.4342812299728394
  - 2.6539502143859863
  - 2.0612621307373047
  - 3.4648163318634033
  - 2.3552803993225098
  - 2.994277000427246
  - -2.0787930488586426
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06075_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
