modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: counties
  choice_column: lcm_county_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.5565026998519897
  - -3.6413400173187256
  - 0.9265845417976379
  - 3.155463218688965
  max_iter: null
  model_expression: st_mean_home_value + st_total_hh + st_total_jobs + st_total_units
    - 1
  name: elcm_county_0_pf
  out_alt_filters: (vacant_job_spaces > 0)
  out_alternatives: null
  out_chooser_filters: (lcm_county_id == "-1") & (agg_sector=="0")
  out_choosers: null
  out_column: lcm_county_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
