modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.05275413766503334
  - 0.058773916214704514
  - 0.9372795820236206
  - 2.7761454582214355
  - 1.1197841167449951
  - -1.6004389524459839
  - -0.9268417358398438
  - -0.012551250867545605
  - -0.3431006371974945
  - -0.002229031641036272
  - 1.0404398441314697
  - 0.2753911316394806
  - -0.16428324580192566
  - 0.09741120785474777
  - 0.14093758165836334
  - -0.49062636494636536
  - -0.11973647773265839
  - -0.8616129159927368
  - 0.5007983446121216
  - 0.826303243637085
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06097_blocks_3_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06097")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (agg_sector=="3")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
