modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.9196411371231079
  - 2.0228261947631836
  - 0.1532496064901352
  - -0.17923690378665924
  - 1.3752248287200928
  - 0.7390966415405273
  - -1.016917109489441
  - -0.9198529720306396
  - 0.9559142589569092
  - -1.6492772102355957
  - -1.7877322435379028
  - 1.4167149066925049
  - 0.8186450004577637
  - -1.1443740129470825
  - -0.5307727456092834
  - 0.5977427959442139
  - 0.40237048268318176
  - 0.10482601076364517
  - -0.4141504764556885
  - -0.11348259449005127
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06055_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
