modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.8669586181640625
  - -1.2792199850082397
  - 0.544438898563385
  - -1.2031158208847046
  - 0.2345498949289322
  - -0.47921454906463623
  - -0.0023509198799729347
  - -0.7765296697616577
  - 0.40531474351882935
  - 0.4128459393978119
  - 0.1182100921869278
  - 0.009278933517634869
  - 1.1893614530563354
  - -0.9297741651535034
  - 2.5358688831329346
  - 9.19904899597168
  - -5.80404806137085
  - -0.32297006249427795
  - 2.813074827194214
  - 0.8546889424324036
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06013_blocks_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06013")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
