modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.7247933745384216
  - -0.6669172644615173
  - 1.7322031259536743
  - 0.8326146602630615
  - -0.4130040109157562
  - 0.629543125629425
  - -1.0170323848724365
  - -0.7751402854919434
  - -0.6543751955032349
  - -2.28279972076416
  - -0.10646811872720718
  - 0.0008659310988150537
  - 2.497898578643799
  - 2.3815338611602783
  - 1.4199466705322266
  - 0.6744458675384521
  - -0.1365501880645752
  - -1.6852097511291504
  - -0.2882544696331024
  - 0.16454316675662994
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06081_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06081")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
