modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.4219355583190918
  - 0.219163179397583
  - 0.005768823903053999
  - -2.075000286102295
  - -0.786659836769104
  - -0.1703687608242035
  - -1.5584076642990112
  - -0.8544396758079529
  - -0.6246255040168762
  - 0.30696868896484375
  - -0.44895657896995544
  - 1.053454041481018
  - -5.551801681518555
  - -2.4605839252471924
  - 4.879146099090576
  - 2.6409733295440674
  - -3.910477638244629
  - 1.5894452333450317
  - 1.4933580160140991
  - 0.0635310485959053
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06001_blocks_2_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (agg_sector=="2")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
