modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -2.5185587406158447
  - -0.9776306748390198
  - 2.7498693466186523
  - -1.1475555896759033
  - 0.5176764726638794
  - -0.273167222738266
  - -0.0038810758851468563
  - -0.9659252762794495
  - 0.5653271079063416
  - -0.9142462015151978
  - -0.0013326734770089388
  - 0.0005508956965059042
  - 2.870182752609253
  - -3.1576480865478516
  - -0.428188681602478
  - -4.2475666999816895
  - -1.1744041442871094
  - 0.002796984277665615
  - -6.625335216522217
  - 5.973031044006348
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06041_blocks_4_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06041")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (agg_sector=="4")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
