modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: counties
  choice_column: lcm_county_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.17925108969211578
  - 0.6120930910110474
  - 0.3121219873428345
  - -0.13316534459590912
  max_iter: null
  model_expression: st_mean_home_value + st_total_hh + st_total_jobs + st_total_units
    - 1
  name: elcm_county_1_pf
  out_alt_filters: (vacant_job_spaces > 0)
  out_alternatives: null
  out_chooser_filters: (lcm_county_id == "-1") & (agg_sector=="1")
  out_choosers: null
  out_column: lcm_county_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
