modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.23299235105514526
  - -0.6300572752952576
  - 1.590364933013916
  - -0.104410320520401
  - 0.8218572735786438
  - 0.21819479763507843
  - -0.004753785207867622
  - -0.025298215448856354
  - -0.814952552318573
  - 0.87944096326828
  - -1.008721947669983
  - 0.0006895911647006869
  - 1.273765206336975
  - -0.8643580675125122
  - 1.3731424808502197
  - 4.879366397857666
  - 6.931086540222168
  - 2.0530102252960205
  - 1.687225580215454
  - 0.574245035648346
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06001_blocks_0_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (agg_sector=="0")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
