modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.48433300852775574
  - 0.2605251669883728
  - -0.6499347686767578
  - -0.1611717790365219
  - -1.2712944746017456
  - 0.3507644534111023
  - -1.6671534776687622
  - -0.8432586193084717
  - -1.0002273321151733
  - -0.8917210102081299
  - -0.05854184553027153
  - 0.003468291135504842
  - -0.4347570538520813
  - -0.1522398144006729
  - -3.210131883621216
  - 0.6309022903442383
  - 1.2579518556594849
  - 3.1419458389282227
  - 0.6847382187843323
  - 0.20067442953586578
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06081_blocks_3_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06081")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (agg_sector=="3")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
