modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.8493497967720032
  - 0.5801423788070679
  - 1.0878212451934814
  - -0.6280115842819214
  - -0.22360531985759735
  - 0.4226399064064026
  - -1.4836320877075195
  - -0.7503719925880432
  - 0.23605556786060333
  - 0.45142269134521484
  - -0.444322407245636
  - 2.4478042125701904
  - 0.4137031137943268
  - 4.336236000061035
  - -1.0155218839645386
  - -1.2979152202606201
  - 3.4975297451019287
  - 0.16795876622200012
  - -1.5041437149047852
  - 0.4801597595214844
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06041_blocks_1_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06041")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (agg_sector=="1")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
