modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.481257677078247
  - -1.629374384880066
  - -0.006657056976109743
  - -1.481329321861267
  - -0.4954115152359009
  - 0.31995701789855957
  - -0.0013691196218132973
  - -0.014124182984232903
  - -1.1875114440917969
  - 0.7703984379768372
  - 1.083964467048645
  - 0.8457392454147339
  - -0.5204743146896362
  - -5.329344749450684
  - 2.303515672683716
  - 12.187164306640625
  - 1.4727708101272583
  - -4.9006667137146
  - 9.844352722167969
  - 1.0727792978286743
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06013_blocks_2_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06013")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (agg_sector=="2")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
