modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -3.8693878650665283
  - 0.20238804817199707
  - -1.9873675107955933
  - -3.721762180328369
  - -0.3499943017959595
  - 1.526811122894287
  - -1.5940872430801392
  - -1.097051978111267
  - -0.9130706191062927
  - 1.3298194408416748
  - 0.08874942362308502
  - 1.5115606784820557
  - -3.5960285663604736
  - -9.17656421661377
  - 2.095451593399048
  - 4.35430908203125
  - -0.69025057554245
  - 5.238249778747559
  - -0.09061427414417267
  - -1.7004045248031616
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06081_blocks_2_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06081")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (agg_sector=="2")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
