modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.1718816757202148
  - -2.1555709838867188
  - 0.9341205358505249
  - -0.7635241150856018
  - -0.6056181192398071
  - -1.7793265581130981
  - -0.0077762966975569725
  - -0.18788886070251465
  - 0.2925722301006317
  - 0.3706059455871582
  - 0.005599075462669134
  - 0.004427887499332428
  - 4.020834445953369
  - 4.05619478225708
  - -0.7615712881088257
  - -1.9525725841522217
  - -5.186110496520996
  - -0.7752676606178284
  - 1.0020157098770142
  - -0.6399397253990173
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06081_blocks_5_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06081")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (agg_sector=="5")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
