modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.7687830924987793
  - -0.31549206376075745
  - 0.06877561658620834
  - -1.0753304958343506
  - -0.21925941109657288
  - 0.6638427972793579
  - -1.2745410203933716
  - -1.0736762285232544
  - -0.3875177502632141
  - 0.06659484654664993
  - -0.39526593685150146
  - 1.5314819812774658
  - -5.369929313659668
  - -1.0392684936523438
  - 0.5024752616882324
  - 3.117182970046997
  - 5.5179123878479
  - -2.9211177825927734
  - 1.7061892747879028
  - -0.6094242334365845
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06001_blocks_3_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (agg_sector=="3")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
