modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.33037808537483215
  - -2.087672472000122
  - -0.036410629749298096
  - 1.2915449142456055
  - -1.6312881708145142
  - 0.2915383577346802
  - -0.4043329656124115
  - -0.411695659160614
  - 0.16428586840629578
  - -0.42485925555229187
  - -0.21001511812210083
  - 0.32958418130874634
  - 0.7083435654640198
  - -0.06369605660438538
  - 1.760879635810852
  - 1.7386424541473389
  - 0.6893458962440491
  - -0.36063721776008606
  - -0.6021962761878967
  - 3.104403495788574
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06075_blocks_4_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (agg_sector=="4")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
