modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.1071977615356445
  - 2.334843873977661
  - 0.8487259149551392
  - -5.923478126525879
  - -1.775983214378357
  - 0.23885101079940796
  - -0.09282870590686798
  - -0.6862187385559082
  - -0.9476078152656555
  - 4.595546245574951
  - 3.1681134700775146
  - 2.227113962173462
  - -0.725578784942627
  - 4.160611629486084
  - -0.44197893142700195
  - -3.4355719089508057
  - 3.0886013507843018
  - -0.15453283488750458
  - -1.7823172807693481
  - -8.927620887756348
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06095_blocks_4_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06095")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (agg_sector=="4")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
