modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.06680995225906372
  - -0.57797771692276
  - -0.8026067018508911
  - -1.0113569498062134
  - -1.6465507745742798
  - -2.917158842086792
  - -1.604922890663147
  - -0.7051289081573486
  - -1.0641121864318848
  - 0.40408846735954285
  - 0.49831005930900574
  - 0.001022223848849535
  - 5.748334884643555
  - -4.450215816497803
  - 4.634118556976318
  - 7.06719446182251
  - -4.026474952697754
  - 0.3890969455242157
  - 4.467095851898193
  - 5.501265525817871
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06075_blocks_1_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (agg_sector=="1")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
