modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.587567687034607
  - -0.2997642755508423
  - 0.8930252194404602
  - -0.6613355875015259
  - -0.5298359990119934
  - 0.6394954323768616
  - -0.014143208973109722
  - -0.932147741317749
  - 0.6985762715339661
  - -0.9096053838729858
  - -0.15586720407009125
  - 1.971225380897522
  - 8.02358627319336
  - -9.914366722106934
  - -2.691591262817383
  - -4.220973491668701
  - 1.9830548763275146
  - 0.47200122475624084
  - -0.8520126342773438
  - -1.5311906337738037
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06041_blocks_5_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06041")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (agg_sector=="5")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
