modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -0.7115333080291748
  - 0.549006462097168
  - -0.6886324882507324
  - -1.700505256652832
  - -0.5253289341926575
  - 1.1493526697158813
  - -1.6371859312057495
  - -1.033803939819336
  - -0.4054712653160095
  - 1.5984443426132202
  - -2.5472798347473145
  - 0.0019036130979657173
  - -0.6279775500297546
  - 1.5420613288879395
  - 0.8511956930160522
  - 0.8397318720817566
  - -6.779672622680664
  - 3.9946794509887695
  - -0.4147612452507019
  - -1.008251428604126
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06081_blocks_1_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06081")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (agg_sector=="1")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
