modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.081116795539856
  - -0.2461792528629303
  - -0.03966692462563515
  - -0.6667559742927551
  - -0.10696730762720108
  - -1.323960542678833
  - -0.0006779192481189966
  - -1.059939980506897
  - -0.45450252294540405
  - -0.6204984188079834
  - 0.3142891526222229
  - 0.0036930658388882875
  - -2.8694980144500732
  - 1.957829236984253
  - 2.334066390991211
  - 1.1155277490615845
  - -2.452650308609009
  - -3.808837890625
  - 1.309798240661621
  - 0.6497467756271362
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06085_blocks_2_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06085")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (agg_sector=="2")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
