modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.1549927145242691
  - -1.2349920272827148
  - 0.47474583983421326
  - 0.11967064440250397
  - -0.9841530919075012
  - -0.0824970230460167
  - -1.1283023357391357
  - -0.630479097366333
  - -0.8838903903961182
  - -0.9030007123947144
  - 0.5591350793838501
  - 1.1358423233032227
  - -4.135742664337158
  - 1.1183775663375854
  - 0.04972625523805618
  - 0.8852812051773071
  - 1.7207791805267334
  - 0.749074399471283
  - -0.8192906379699707
  - 0.8684863448143005
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06085_blocks_4_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06085")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (agg_sector=="4")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
