modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.11990298330783844
  - 0.24231860041618347
  - 0.6906561851501465
  - -0.8067367076873779
  - -0.7891854643821716
  - 0.01151349302381277
  - -0.005615698639303446
  - -0.0032844077795743942
  - -0.46423640847206116
  - 0.4749473035335541
  - -0.7493579387664795
  - 0.005811634473502636
  - -0.3806053400039673
  - -0.647932231426239
  - 6.370639324188232
  - -0.40095987915992737
  - -6.5941853523254395
  - -2.4432034492492676
  - 5.122713565826416
  - -0.14047713577747345
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06001_blocks_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
