modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - -1.7556720972061157
  - -0.010395501740276814
  - -0.1286834329366684
  - -0.16170354187488556
  - 0.19791129231452942
  - -0.37179216742515564
  - -1.712723970413208
  - -1.2332006692886353
  - -0.8626530766487122
  - -0.6794278025627136
  - 0.8220295906066895
  - 0.0009456581901758909
  - -0.27207621932029724
  - -0.5557347536087036
  - -0.17259597778320312
  - -0.08448345959186554
  - -0.2559216618537903
  - -0.4108017683029175
  - -0.02824416011571884
  - 1.29463529586792
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06055_blocks_5_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (agg_sector=="5")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
