modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_job_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: jobs
  constrained_choices: true
  fitted_parameters:
  - 0.5152499079704285
  - 1.3557275533676147
  - -0.7138620615005493
  - 0.2573831081390381
  - -2.0651943683624268
  - -1.8511459827423096
  - -1.5183560848236084
  - -0.4353973865509033
  - -0.9446250796318054
  - -0.3403274118900299
  - 0.7736164927482605
  - 0.212999626994133
  - 2.61741304397583
  - 1.2123969793319702
  - 1.9754952192306519
  - 0.6323407888412476
  - -0.39380359649658203
  - 0.936180830001831
  - 1.5824940204620361
  - 4.129364013671875
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_total_units + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov - 1
  name: elcm_06075_blocks_2_pf
  out_alt_filters: (vacant_job_spaces > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (agg_sector=="2")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
