modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.0644680994559903
    - 0.11021094522878602
    - 0.17673921109007557
    - -0.05572479178196002
    - -0.07838708133857737
    - -0.3510297182032814
    - -0.13017252613031655
    - 0.32443600134454664
    - 0.21446801749079417
    - -0.06920260642722802
    - 0.4951178298442113
    - 0.028531471336988353
    - 0.06163211765382057
    - -0.051936651930960025
    - 0.19233004155714808
    - -0.1103815862539035
    - 0.1194334665716636
    - -0.22803946302367478
    - 0.32143228045630495
    - -0.67332980950398
    - 0.4061551661026485
    - -0.26381562126373187
    - -0.0047083780608219335
    - 0.2074314639764135
    - 0.08742731224511512
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          33,473\nModel:\
        \         Multinomial Logit   Df Residuals:              33,448\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.090\nTime:       \
        \               18:26   Pseudo R-bar-squ.:          0.089\nAIC:          \
        \       280,719.220   Log-Likelihood:      -140,334.610\nBIC:            \
        \     280,929.683   LL-Null:             -154,148.862\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.0645     0.009   227.091  \
        \   0.000             \nst_bg_mean_age_of_head                       0.1102\
        \     0.013     8.373     0.000             \nst_bg_mean_children        \
        \                  0.1767     0.011    16.318     0.000             \nst_bg_mean_year_built\
        \                       -0.0557     0.012    -4.714     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.0784     0.013    -5.957\
        \     0.000             \nst_bg_prop_hh_rent                          -0.3510\
        \     0.012   -29.710     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1302     0.016    -8.176     0.000             \nst_bg_ratio_households_to_units\
        \              0.3244     0.022    14.602     0.000             \nst_bg_total_units\
        \                            0.2145     0.015    14.709     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.0692     0.006   -11.715\
        \     0.000             \nst_density_units_90pct_plus                  0.4951\
        \     0.005   106.351     0.000             \nst_pred_built_out_sf       \
        \                  0.0285     0.004     7.335     0.000             \nst_pred_rich_owned_antique\
        \                   0.0616     0.004    16.987     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0519     0.010    -5.129     0.000             \nst_tracts_income_segment_6_hh\
        \                0.1923     0.007    26.274     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1104     0.010   -11.517     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.1194     0.102     1.176     0.240             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.2280     0.023    -9.925     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.3214     0.049     6.586     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.6733     0.046   -14.526     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.4062     0.089     4.573     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.2638     0.052    -5.050     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.0047     0.095    -0.050     0.960             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.2074     0.042     4.896     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.0874     0.119     0.735     0.462             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
