modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.9606811965385837
    - 0.06586725366187157
    - 0.10061451775396565
    - -0.07011055893763705
    - 0.011813990356345902
    - 0.8585656119194949
    - -0.1853066526040736
    - 0.5660569510004243
    - 0.055878120838595245
    - -0.353341919443924
    - 0.487031358063007
    - -0.025014484991053878
    - -0.07685549563352222
    - -0.2661599548295627
    - 0.0712227938042925
    - 0.16509128952873833
    - -0.5837357686119841
    - -0.0009495126390677511
    - -0.2878420531943658
    - -0.0556311905586333
    - 0.7210408393330472
    - -0.6304202236746557
    - 0.6054572687871356
    - -0.38732466527028275
    - 0.48858238296199313
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          49,193\nModel:\
        \         Multinomial Logit   Df Residuals:              49,168\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.262\nTime:       \
        \               20:40   Pseudo R-bar-squ.:          0.262\nAIC:          \
        \       334,344.071   Log-Likelihood:      -167,147.036\nBIC:            \
        \     334,564.159   LL-Null:             -226,542.137\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.9607     0.007   417.057  \
        \   0.000             \nst_bg_mean_age_of_head                       0.0659\
        \     0.008     7.795     0.000             \nst_bg_mean_children        \
        \                  0.1006     0.006    16.956     0.000             \nst_bg_mean_year_built\
        \                       -0.0701     0.010    -7.238     0.000            \
        \ \nst_bg_median_value_13_acs                    0.0118     0.008     1.441\
        \     0.150             \nst_bg_prop_hh_rent                           0.8586\
        \     0.009    97.623     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1853     0.009   -20.560     0.000             \nst_bg_ratio_households_to_units\
        \              0.5661     0.015    37.711     0.000             \nst_bg_total_units\
        \                            0.0559     0.009     5.893     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3533     0.007   -51.908\
        \     0.000             \nst_density_units_90pct_plus                  0.4870\
        \     0.003   140.679     0.000             \nst_pred_built_out_sf       \
        \                 -0.0250     0.008    -3.118     0.002             \nst_pred_rich_owned_antique\
        \                  -0.0769     0.014    -5.573     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.2662     0.011   -23.301     0.000             \nst_tracts_income_segment_6_hh\
        \                0.0712     0.008     8.989     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1651     0.020     8.137     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.5837     0.062    -9.453     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0009     0.018    -0.052     0.959             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.2878     0.035    -8.162     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.0556     0.043    -1.288     0.198             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.7210     0.070    10.366     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.6304     0.062   -10.212     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.6055     0.084     7.198     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.3873     0.033   -11.737     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.4886     0.061     8.023     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
