modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.6068146153838017
    - 0.15874384191593535
    - -0.24966423039101848
    - 0.0023232552293537697
    - -0.24017155490891262
    - 3.209864979843582
    - 0.1375830904139825
    - 0.31514169230861216
    - -0.11673832892334175
    - -0.27879853979076924
    - 0.5314509917089744
    - -2.7024118510233865
    - -2.307374064692341
    - -0.025924262404466904
    - -0.04886226917257706
    - 0.2424690476319252
    - 1.1785468130504912
    - -0.36022828927060957
    - 0.8925136763157681
    - 1.7674409019932742
    - -0.879623730920486
    - 1.5583371451061467
    - -3.2424625880863194
    - -0.9244050539919423
    - -0.2888369371137087
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            979\nModel:\
        \         Multinomial Logit   Df Residuals:                954\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.275\nTime:          \
        \            19:46   Pseudo R-bar-squ.:         0.269\nAIC:              \
        \     6,590.300   Log-Likelihood:       -3,270.150\nBIC:                 \
        \  6,712.463   LL-Null:              -4,508.462\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.6068     0.046    56.752  \
        \   0.000             \nst_bg_mean_age_of_head                       0.1587\
        \     0.053     2.989     0.003             \nst_bg_mean_children        \
        \                 -0.2497     0.056    -4.452     0.000             \nst_bg_mean_year_built\
        \                        0.0023     0.069     0.034     0.973            \
        \ \nst_bg_median_value_13_acs                   -0.2402     0.084    -2.849\
        \     0.004             \nst_bg_prop_hh_rent                           3.2099\
        \     0.195    16.482     0.000             \nst_bg_prop_units_sf        \
        \                  0.1376     0.074     1.855     0.064             \nst_bg_ratio_households_to_units\
        \              0.3151     0.132     2.391     0.017             \nst_bg_total_units\
        \                           -0.1167     0.141    -0.830     0.407        \
        \     \nst_density_jobs_90pct_plus                  -0.2788     0.051    -5.415\
        \     0.000             \nst_density_units_90pct_plus                  0.5315\
        \     0.026    20.519     0.000             \nst_pred_built_out_sf       \
        \                 -2.7024       nan       nan       nan             \nst_pred_rich_owned_antique\
        \                  -2.3074       nan       nan       nan             \nst_tracts_income_segment_1_hh\
        \               -0.0259     0.055    -0.474     0.635             \nst_tracts_income_segment_6_hh\
        \               -0.0489     0.115    -0.424     0.671             \nst_zones_density_units_ave_5_min_sov\
        \         0.2425     0.071     3.403     0.001             \nst_zones_income_6_hh_sum_10_min_sov\
        \          1.1785     0.759     1.553     0.121             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.3602     0.278    -1.296     0.195             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.8925     0.655     1.363     0.173             \nst_zones_jobs_2_sum_5_min_sov\
        \                1.7674     0.583     3.030     0.002             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.8796     0.917    -0.960     0.337             \nst_zones_jobs_4_sum_5_min_sov\
        \                1.5583     0.650     2.398     0.016             \nst_zones_jobs_5_sum_5_min_sov\
        \               -3.2425     1.175    -2.759     0.006             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.9244     0.814    -1.136     0.256             \nst_zones_total_units_sum_10_min_sov\
        \         -0.2888     0.961    -0.300     0.764             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
