modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 1.852736292807155
    - 0.7567969865114422
    - 0.25357364899108004
    - -0.000792140491175748
    - 0.03086042048326816
    - 0.06220622455500893
    - 0.15766718845201708
    - 0.22453652234006136
    - 0.0900909708218888
    - -0.22506852271386313
    - -0.2143906626148359
    - -0.012898690217951012
    - 0.021158416163811332
    - -0.11591395039897666
    - 0.5630339700468444
    - -0.17241263491762104
    - -2.5223679557902425
    - 0.4405895597960835
    - 1.3454272382191765
    - 0.05206467794456779
    - 0.8127801750809439
    - -0.48476674279158255
    - 0.39406046460788574
    - -1.1460416889039542
    - 1.2304218179074904
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          8,137\nModel:\
        \         Multinomial Logit   Df Residuals:              8,112\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.084\nTime:          \
        \            19:08   Pseudo R-bar-squ.:         0.084\nAIC:              \
        \    68,676.488   Log-Likelihood:      -34,313.244\nBIC:                 \
        \ 68,851.592   LL-Null:             -37,472.270\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    1.8527     0.014   128.354  \
        \   0.000             \nst_bg_mean_age_of_head                       0.7568\
        \     0.024    31.307     0.000             \nst_bg_mean_children        \
        \                  0.2536     0.021    12.072     0.000             \nst_bg_mean_year_built\
        \                       -0.0008     0.027    -0.029     0.977            \
        \ \nst_bg_median_value_13_acs                    0.0309     0.021     1.452\
        \     0.146             \nst_bg_prop_hh_rent                           0.0622\
        \     0.035     1.801     0.072             \nst_bg_prop_units_sf        \
        \                  0.1577     0.030     5.235     0.000             \nst_bg_ratio_households_to_units\
        \              0.2245     0.033     6.893     0.000             \nst_bg_total_units\
        \                            0.0901     0.045     1.992     0.046        \
        \     \nst_density_jobs_90pct_plus                  -0.2251     0.031    -7.261\
        \     0.000             \nst_density_units_90pct_plus                 -0.2144\
        \     0.021   -10.024     0.000             \nst_pred_built_out_sf       \
        \                 -0.0129     0.010    -1.307     0.191             \nst_pred_rich_owned_antique\
        \                   0.0212     0.031     0.681     0.496             \nst_tracts_income_segment_1_hh\
        \               -0.1159     0.027    -4.320     0.000             \nst_tracts_income_segment_6_hh\
        \                0.5630     0.062     9.080     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1724     0.026    -6.617     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -2.5224     0.388    -6.502     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.4406     0.082     5.396     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                1.3454     0.216     6.232     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.0521     0.188     0.278     0.781             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.8128     0.328     2.475     0.013             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.4848     0.188    -2.582     0.010             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.3941     0.325     1.212     0.226             \nst_zones_total_jobs_sum_20_min_sov\
        \          -1.1460     0.193    -5.939     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          1.2304     0.526     2.340     0.019             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
