modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.6366546388118928
    - 0.33560518400205136
    - -0.05194189318436375
    - 0.36470347207827924
    - -0.5019163318423111
    - 1.5373598122690704
    - 0.18147854720682693
    - 0.37893773542938775
    - -0.45701781532942054
    - -0.32954920261351656
    - 0.2135279373024727
    - 0.03374433116020367
    - -2.1371918671518433
    - -0.17412919508137797
    - 0.5346891533955074
    - 0.18396630392468585
    - 0.903203156634872
    - 0.9570561542931363
    - 1.8964586220034625
    - 1.8284080155974534
    - 0.3452572545760402
    - 1.0258296385662382
    - -6.167624800252426
    - -0.26840956855966824
    - -0.8247889684491864
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum +  + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            478\nModel:\
        \         Multinomial Logit   Df Residuals:                453\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.139\nTime:          \
        \            17:45   Pseudo R-bar-squ.:         0.127\nAIC:              \
        \     3,842.114   Log-Likelihood:       -1,896.057\nBIC:                 \
        \  3,946.355   LL-Null:              -2,201.271\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.6367     0.071    37.360  \
        \   0.000             \nst_bg_mean_age_of_head                       0.3356\
        \     0.074     4.557     0.000             \nst_bg_mean_children        \
        \                 -0.0519     0.082    -0.631     0.528             \nst_bg_mean_year_built\
        \                        0.3647     0.094     3.878     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.5019     0.115    -4.373\
        \     0.000             \nst_bg_prop_hh_rent                           1.5374\
        \     0.277     5.546     0.000             \nst_bg_prop_units_sf        \
        \                  0.1815     0.103     1.755     0.079             \nst_bg_ratio_households_to_units\
        \              0.3789     0.177     2.141     0.032             \nst_bg_total_units\
        \                           -0.4570     0.188    -2.436     0.015        \
        \     \nst_density_jobs_90pct_plus                  -0.3295     0.095    -3.454\
        \     0.001             \nst_density_units_90pct_plus                  0.2135\
        \     0.059     3.622     0.000             \nst_pred_built_out_sf       \
        \                  0.0337     0.089     0.378     0.706             \nst_pred_rich_owned_antique\
        \                  -2.1372     3.264    -0.655     0.513             \nst_tracts_income_segment_1_hh\
        \               -0.1741     0.075    -2.330     0.020             \nst_tracts_income_segment_6_hh\
        \                0.5347     0.141     3.791     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1840     0.099     1.859     0.063             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.9032     1.018     0.888     0.375             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.9571     0.367     2.610     0.009             \nst_zones_jobs_1_sum_5_min_sov\
        \                1.8965     0.879     2.158     0.031             \nst_zones_jobs_2_sum_5_min_sov\
        \                1.8284     0.816     2.241     0.025             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.3453     1.181     0.292     0.770             \nst_zones_jobs_4_sum_5_min_sov\
        \                1.0258     0.895     1.146     0.252             \nst_zones_jobs_5_sum_5_min_sov\
        \               -6.1676     1.470    -4.196     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.2684     1.013    -0.265     0.791             \nst_zones_total_units_sum_10_min_sov\
        \         -0.8248     1.381    -0.597     0.550             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
