modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.993689581555184
    - 0.5898663287078689
    - 0.08376661973856032
    - -0.004311306965782225
    - -0.008473370089673844
    - 0.9668524496167397
    - -0.10881740376211792
    - 0.41856427603871194
    - 0.0014160492463185235
    - -0.3432274641251932
    - 0.47502895286128966
    - 0.006821608741392493
    - -0.08910777375649995
    - -0.30510885916226216
    - -0.009382844007879998
    - -0.06800271032230526
    - -0.6941570799940245
    - -0.04122017436427061
    - -0.5719014206591924
    - 0.03661983117193142
    - 0.30810316279241384
    - -0.8042380024509944
    - 1.51075767761748
    - -0.31917457439676966
    - 0.4520216351294437
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         11,141\nModel:\
        \         Multinomial Logit   Df Residuals:             11,116\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.220\nTime:          \
        \            21:01   Pseudo R-bar-squ.:         0.220\nAIC:              \
        \    80,038.814   Log-Likelihood:      -39,994.407\nBIC:                 \
        \ 80,221.773   LL-Null:             -51,306.201\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.9937     0.012   254.867  \
        \   0.000             \nst_bg_mean_age_of_head                       0.5899\
        \     0.017    33.868     0.000             \nst_bg_mean_children        \
        \                  0.0838     0.013     6.460     0.000             \nst_bg_mean_year_built\
        \                       -0.0043     0.020    -0.215     0.830            \
        \ \nst_bg_median_value_13_acs                   -0.0085     0.017    -0.495\
        \     0.621             \nst_bg_prop_hh_rent                           0.9669\
        \     0.018    54.187     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1088     0.018    -6.031     0.000             \nst_bg_ratio_households_to_units\
        \              0.4186     0.033    12.679     0.000             \nst_bg_total_units\
        \                            0.0014     0.022     0.065     0.948        \
        \     \nst_density_jobs_90pct_plus                  -0.3432     0.015   -23.500\
        \     0.000             \nst_density_units_90pct_plus                  0.4750\
        \     0.007    63.814     0.000             \nst_pred_built_out_sf       \
        \                  0.0068     0.013     0.516     0.606             \nst_pred_rich_owned_antique\
        \                  -0.0891     0.028    -3.200     0.001             \nst_tracts_income_segment_1_hh\
        \               -0.3051     0.024   -12.678     0.000             \nst_tracts_income_segment_6_hh\
        \               -0.0094     0.016    -0.570     0.569             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0680     0.036    -1.905     0.057             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.6942     0.126    -5.510     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0412     0.039    -1.055     0.291             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.5719     0.073    -7.853     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.0366     0.088     0.417     0.676             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.3081     0.148     2.087     0.037             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.8042     0.130    -6.189     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                1.5108     0.179     8.428     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.3192     0.067    -4.778     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.4520     0.127     3.560     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
