modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.6148058366384066
    - 0.5561009854580478
    - 0.35878915531064415
    - 0.19833530207298633
    - -0.38917706692502424
    - 0.2365256887510793
    - 0.32587698952064065
    - 0.2263872784371767
    - 0.09564397547039832
    - -0.33983826416596963
    - 0.05966617296515083
    - -0.09942278362033252
    - 0.057808543856697044
    - -0.266635830785379
    - 0.23779830217948755
    - 0.13527129788221545
    - -0.1108961297125235
    - 0.14924821832723117
    - 0.1689040813254031
    - -0.40931252191676454
    - 0.08570462009455511
    - -0.05156062231821532
    - -0.1453814778501508
    - -0.7400729378330462
    - 0.8808369808167275
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          53,274\nModel:\
        \         Multinomial Logit   Df Residuals:              53,249\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.110\nTime:       \
        \               18:14   Pseudo R-bar-squ.:          0.110\nAIC:          \
        \       436,536.447   Log-Likelihood:      -218,243.223\nBIC:            \
        \     436,758.527   LL-Null:             -245,335.836\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.6148     0.005   488.339  \
        \   0.000             \nst_bg_mean_age_of_head                       0.5561\
        \     0.010    56.855     0.000             \nst_bg_mean_children        \
        \                  0.3588     0.007    51.539     0.000             \nst_bg_mean_year_built\
        \                        0.1983     0.008    24.987     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.3892     0.009   -41.459\
        \     0.000             \nst_bg_prop_hh_rent                           0.2365\
        \     0.009    25.642     0.000             \nst_bg_prop_units_sf        \
        \                  0.3259     0.010    32.981     0.000             \nst_bg_ratio_households_to_units\
        \              0.2264     0.010    22.009     0.000             \nst_bg_total_units\
        \                            0.0956     0.009    10.648     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3398     0.013   -26.231\
        \     0.000             \nst_density_units_90pct_plus                  0.0597\
        \     0.007     8.381     0.000             \nst_pred_built_out_sf       \
        \                 -0.0994     0.005   -21.347     0.000             \nst_pred_rich_owned_antique\
        \                   0.0578     0.007     7.751     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.2666     0.007   -36.833     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2378     0.007    34.375     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1353     0.013    10.244     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.1109     0.059    -1.869     0.062             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.1492     0.017     8.669     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.1689     0.043     3.913     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.4093     0.040   -10.347     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.0857     0.061     1.412     0.158             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.0516     0.040    -1.282     0.200             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.1454     0.067    -2.161     0.031             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.7401     0.037   -20.101     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.8808     0.068    13.016     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
