modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.2294059198413967
    - 0.18837315646448582
    - -0.31182049784446897
    - 0.08304372529012118
    - -0.4053322616867543
    - 1.5954719626926177
    - -0.22581634459286837
    - 0.44820539648791646
    - -0.24821942474790318
    - -0.017589315696553504
    - 0.7435980921340809
    - 0.021599067330511344
    - -1.9698646236430646
    - 0.014731397993462157
    - -0.12714724208797856
    - -0.2336562171152287
    - 0.8064693937781044
    - 0.7187230835771301
    - 0.8771341889372987
    - 0.22207605263792884
    - 0.3182190446302094
    - 1.5750736333568756
    - -5.37871592449374
    - 2.097512514399947
    - -1.1524449498653577
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            708\nModel:\
        \         Multinomial Logit   Df Residuals:                683\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.378\nTime:          \
        \            19:46   Pseudo R-bar-squ.:         0.370\nAIC:              \
        \     4,108.958   Log-Likelihood:       -2,029.479\nBIC:                 \
        \  4,223.019   LL-Null:              -3,260.460\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.2294     0.057    39.251  \
        \   0.000             \nst_bg_mean_age_of_head                       0.1884\
        \     0.071     2.647     0.008             \nst_bg_mean_children        \
        \                 -0.3118     0.065    -4.801     0.000             \nst_bg_mean_year_built\
        \                        0.0830     0.086     0.960     0.337            \
        \ \nst_bg_median_value_13_acs                   -0.4053     0.178    -2.272\
        \     0.023             \nst_bg_prop_hh_rent                           1.5955\
        \     0.088    18.155     0.000             \nst_bg_prop_units_sf        \
        \                 -0.2258     0.076    -2.955     0.003             \nst_bg_ratio_households_to_units\
        \              0.4482     0.153     2.925     0.003             \nst_bg_total_units\
        \                           -0.2482     0.139    -1.786     0.074        \
        \     \nst_density_jobs_90pct_plus                  -0.0176     0.089    -0.197\
        \     0.844             \nst_density_units_90pct_plus                  0.7436\
        \     0.029    25.488     0.000             \nst_pred_built_out_sf       \
        \                  0.0216     0.127     0.170     0.865             \nst_pred_rich_owned_antique\
        \                  -1.9699     3.752    -0.525     0.600             \nst_tracts_income_segment_1_hh\
        \                0.0147     0.057     0.258     0.796             \nst_tracts_income_segment_6_hh\
        \               -0.1271     0.331    -0.384     0.701             \nst_zones_density_units_ave_5_min_sov\
        \        -0.2337     0.120    -1.948     0.051             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.8065     0.734     1.099     0.272             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.7187     0.254     2.834     0.005             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.8771     0.580     1.511     0.131             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.2221     0.525     0.423     0.672             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.3182     0.678     0.469     0.639             \nst_zones_jobs_4_sum_5_min_sov\
        \                1.5751     0.612     2.573     0.010             \nst_zones_jobs_5_sum_5_min_sov\
        \               -5.3787     1.294    -4.156     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           2.0975     0.855     2.452     0.014             \nst_zones_total_units_sum_10_min_sov\
        \         -1.1524     1.146    -1.006     0.315             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
