modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.0286337992775696
    - 0.40404563772811636
    - 0.46184817276553225
    - 0.06678608326402012
    - 0.0853550449864695
    - -0.14795458020366967
    - 0.15258358147793175
    - 0.44420897190662467
    - 0.06135586962602641
    - -0.18531940806247743
    - -0.169870508467968
    - 0.0038192861153953043
    - -0.0017792916419252782
    - -0.06275577645845097
    - 0.6599869395783675
    - -0.191579205230797
    - -1.377828554196332
    - 0.1917803141512856
    - -0.31163565440852187
    - 1.118099462213452
    - 0.3754721632147668
    - -1.1059820695569786
    - -0.12626851560653557
    - 0.5021243975826437
    - 0.8930517776955305
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          5,838\nModel:\
        \         Multinomial Logit   Df Residuals:              5,813\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.097\nTime:          \
        \            18:22   Pseudo R-bar-squ.:         0.097\nAIC:              \
        \    48,579.285   Log-Likelihood:      -24,264.642\nBIC:                 \
        \ 48,746.089   LL-Null:             -26,884.984\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.0286     0.027    73.943  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4040\
        \     0.031    12.928     0.000             \nst_bg_mean_children        \
        \                  0.4618     0.023    20.098     0.000             \nst_bg_mean_year_built\
        \                        0.0668     0.031     2.145     0.032            \
        \ \nst_bg_median_value_13_acs                    0.0854     0.028     3.017\
        \     0.003             \nst_bg_prop_hh_rent                          -0.1480\
        \     0.041    -3.573     0.000             \nst_bg_prop_units_sf        \
        \                  0.1526     0.037     4.138     0.000             \nst_bg_ratio_households_to_units\
        \              0.4442     0.042    10.604     0.000             \nst_bg_total_units\
        \                            0.0614     0.060     1.029     0.304        \
        \     \nst_density_jobs_90pct_plus                  -0.1853     0.030    -6.124\
        \     0.000             \nst_density_units_90pct_plus                 -0.1699\
        \     0.024    -7.132     0.000             \nst_pred_built_out_sf       \
        \                  0.0038     0.011     0.340     0.734             \nst_pred_rich_owned_antique\
        \                  -0.0018     0.046    -0.039     0.969             \nst_tracts_income_segment_1_hh\
        \               -0.0628     0.031    -2.029     0.042             \nst_tracts_income_segment_6_hh\
        \                0.6600     0.082     8.069     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1916     0.032    -6.047     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -1.3778     0.478    -2.884     0.004             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.1918     0.093     2.072     0.038             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.3116     0.268    -1.162     0.245             \nst_zones_jobs_2_sum_5_min_sov\
        \                1.1181     0.224     4.994     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.3755     0.398     0.945     0.345             \nst_zones_jobs_4_sum_5_min_sov\
        \               -1.1060     0.227    -4.873     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.1263     0.362    -0.349     0.727             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.5021     0.258     1.943     0.052             \nst_zones_total_units_sum_10_min_sov\
        \          0.8931     0.655     1.364     0.173             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
