modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06001")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06001") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.775155371279208
    - 0.30921849753991154
    - -0.3908995636187262
    - 0.04428740973709349
    - -0.45351133841467434
    - 0.03763152376997148
    - 0.08688864575943991
    - 0.21692539838461805
    - 0.14422461930340036
    - -0.19424422239074451
    - 0.3650516522198286
    - -0.11566464394264744
    - 0.05081991014764984
    - -0.27491694927750043
    - 0.26116580452754634
    - 0.05704769057506381
    - -0.3746446098963677
    - 0.01329690334268276
    - -0.31202956906401835
    - 0.8431979788718779
    - 0.36068354115137974
    - -1.2437052011947427
    - 0.337731432382104
    - 0.08208226265717605
    - 0.20346614640490807
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum +  + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06001_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001") & (zone_id
        == zone_id) & (zone_id == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          6,241\nModel:\
        \         Multinomial Logit   Df Residuals:              6,216\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.119\nTime:          \
        \            17:38   Pseudo R-bar-squ.:         0.118\nAIC:              \
        \    50,685.677   Log-Likelihood:      -25,317.839\nBIC:                 \
        \ 50,854.150   LL-Null:             -28,740.867\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.7752     0.014   200.251  \
        \   0.000             \nst_bg_mean_age_of_head                       0.3092\
        \     0.023    13.649     0.000             \nst_bg_mean_children        \
        \                 -0.3909     0.019   -20.194     0.000             \nst_bg_mean_year_built\
        \                        0.0443     0.020     2.205     0.027            \
        \ \nst_bg_median_value_13_acs                   -0.4535     0.027   -16.586\
        \     0.000             \nst_bg_prop_hh_rent                           0.0376\
        \     0.028     1.341     0.180             \nst_bg_prop_units_sf        \
        \                  0.0869     0.025     3.522     0.000             \nst_bg_ratio_households_to_units\
        \              0.2169     0.029     7.607     0.000             \nst_bg_total_units\
        \                            0.1442     0.022     6.416     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1942     0.018   -10.570\
        \     0.000             \nst_density_units_90pct_plus                  0.3651\
        \     0.011    33.470     0.000             \nst_pred_built_out_sf       \
        \                 -0.1157     0.017    -6.676     0.000             \nst_pred_rich_owned_antique\
        \                   0.0508     0.009     5.593     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.2749     0.024   -11.629     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2612     0.030     8.739     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.0570     0.029     1.940     0.052             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.3746     0.135    -2.770     0.006             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.0133     0.047     0.284     0.776             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.3120     0.109    -2.859     0.004             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.8432     0.104     8.123     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.3607     0.143     2.529     0.011             \nst_zones_jobs_4_sum_5_min_sov\
        \               -1.2437     0.143    -8.727     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.3377     0.214     1.580     0.114             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.0821     0.082     0.996     0.319             \nst_zones_total_units_sum_10_min_sov\
        \          0.2035     0.158     1.292     0.197             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
