modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.570909963232158
    - 0.7250372888745144
    - -0.013853997390499438
    - 0.1473629751619873
    - -0.059148076086335516
    - 0.4635934694492909
    - 0.2809301437505238
    - 0.3678873660734413
    - 0.04310784899064291
    - -0.4928513605952089
    - 0.10121885685726525
    - -0.06657519058772658
    - 0.08432077692595973
    - -0.2587119648049831
    - 0.1232798989993569
    - -0.0963004404094411
    - -0.39325594715687734
    - -0.07967297092652609
    - -0.6678503662517635
    - -0.2806469030662989
    - 1.446014884619567
    - -0.5763534504116768
    - 0.5689192442923823
    - -0.4897535624067695
    - 0.48946775609942544
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          45,243\nModel:\
        \         Multinomial Logit   Df Residuals:              45,218\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.101\nTime:       \
        \               19:24   Pseudo R-bar-squ.:          0.101\nAIC:          \
        \       374,567.790   Log-Likelihood:      -187,258.895\nBIC:            \
        \     374,785.785   LL-Null:             -208,351.715\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.5709     0.006   450.949  \
        \   0.000             \nst_bg_mean_age_of_head                       0.7250\
        \     0.010    72.373     0.000             \nst_bg_mean_children        \
        \                 -0.0139     0.007    -1.868     0.062             \nst_bg_mean_year_built\
        \                        0.1474     0.010    15.476     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.0591     0.009    -6.402\
        \     0.000             \nst_bg_prop_hh_rent                           0.4636\
        \     0.012    37.275     0.000             \nst_bg_prop_units_sf        \
        \                  0.2809     0.011    26.499     0.000             \nst_bg_ratio_households_to_units\
        \              0.3679     0.017    22.089     0.000             \nst_bg_total_units\
        \                            0.0431     0.011     3.942     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.4929     0.010   -47.487\
        \     0.000             \nst_density_units_90pct_plus                  0.1012\
        \     0.006    16.653     0.000             \nst_pred_built_out_sf       \
        \                 -0.0666     0.007   -10.112     0.000             \nst_pred_rich_owned_antique\
        \                   0.0843     0.005    16.481     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.2587     0.010   -25.052     0.000             \nst_tracts_income_segment_6_hh\
        \                0.1233     0.008    16.197     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0963     0.016    -6.137     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.3933     0.057    -6.919     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0797     0.019    -4.164     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.6679     0.035   -19.282     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.2806     0.038    -7.387     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.4460     0.071    20.447     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.5764     0.064    -8.936     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.5689     0.084     6.758     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.4898     0.029   -16.801     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.4895     0.058     8.418     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
