modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.4553847736665695
    - 0.6876961469076922
    - 0.01339092878155427
    - 0.349467628577705
    - -0.3783771282925785
    - 0.3698233269347023
    - 0.44161174548281285
    - 0.5852807682636983
    - 0.24638368453898102
    - -0.3404965733510904
    - 0.1115476695991826
    - -0.028779793000376967
    - 0.028569163504550254
    - -0.10716396034015872
    - 0.24250450773179616
    - 0.16605537441683182
    - 0.3605890502144057
    - -0.03519085397930509
    - 0.22945221278267477
    - -0.17673667680912988
    - 0.263073346717865
    - -0.9719846008968059
    - 0.7228844242349128
    - 1.2098763895199223
    - -1.5950507441612691
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          29,648\nModel:\
        \         Multinomial Logit   Df Residuals:              29,623\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.108\nTime:       \
        \               18:31   Pseudo R-bar-squ.:          0.108\nAIC:          \
        \       243,631.968   Log-Likelihood:      -121,790.984\nBIC:            \
        \     243,839.397   LL-Null:             -136,534.086\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.4554     0.009   276.591  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6877\
        \     0.014    50.896     0.000             \nst_bg_mean_children        \
        \                  0.0134     0.010     1.327     0.184             \nst_bg_mean_year_built\
        \                        0.3495     0.013    26.180     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.3784     0.013   -29.404\
        \     0.000             \nst_bg_prop_hh_rent                           0.3698\
        \     0.010    36.179     0.000             \nst_bg_prop_units_sf        \
        \                  0.4416     0.012    36.058     0.000             \nst_bg_ratio_households_to_units\
        \              0.5853     0.023    25.058     0.000             \nst_bg_total_units\
        \                            0.2464     0.022    11.402     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3405     0.011   -29.668\
        \     0.000             \nst_density_units_90pct_plus                  0.1115\
        \     0.006    19.717     0.000             \nst_pred_built_out_sf       \
        \                 -0.0288     0.006    -4.968     0.000             \nst_pred_rich_owned_antique\
        \                   0.0286     0.003     8.704     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.1072     0.013    -8.172     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2425     0.011    22.927     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1661     0.012    13.634     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.3606     0.071     5.058     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0352     0.020    -1.718     0.086             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.2295     0.056     4.102     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.1767     0.047    -3.789     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.2631     0.088     2.983     0.003             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.9720     0.062   -15.758     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.7229     0.099     7.294     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           1.2099     0.040    30.195     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -1.5951     0.076   -20.872     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
