modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.5011128597483228
    - 0.9665373162849444
    - -0.14923806896561123
    - 0.37577638598030527
    - -0.38810941513827907
    - 0.4550792821617762
    - 0.49858640272026167
    - 0.592329604452708
    - 0.22218988806088288
    - -0.32573078376454545
    - 0.1305337797865224
    - -0.03688614107522477
    - 0.02104044507917632
    - -0.09150908522290635
    - 0.17634454202469582
    - 0.10775291846041832
    - 0.3200672094368878
    - -0.05151453684671377
    - 0.1394309520535902
    - -0.043965091911320545
    - -0.1156565355394448
    - -0.6277700562275449
    - 0.6337907858513052
    - 1.091963724662457
    - -1.3369017528308396
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          32,677\nModel:\
        \         Multinomial Logit   Df Residuals:              32,652\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.114\nTime:       \
        \               19:18   Pseudo R-bar-squ.:          0.114\nAIC:          \
        \       266,573.464   Log-Likelihood:      -133,261.732\nBIC:            \
        \     266,783.325   LL-Null:             -150,483.146\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.5011     0.006   388.817  \
        \   0.000             \nst_bg_mean_age_of_head                       0.9665\
        \     0.012    77.758     0.000             \nst_bg_mean_children        \
        \                 -0.1492     0.010   -14.735     0.000             \nst_bg_mean_year_built\
        \                        0.3758     0.013    28.741     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.3881     0.012   -31.965\
        \     0.000             \nst_bg_prop_hh_rent                           0.4551\
        \     0.010    46.800     0.000             \nst_bg_prop_units_sf        \
        \                  0.4986     0.012    43.079     0.000             \nst_bg_ratio_households_to_units\
        \              0.5923     0.023    26.314     0.000             \nst_bg_total_units\
        \                            0.2222     0.021    10.454     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3257     0.011   -29.920\
        \     0.000             \nst_density_units_90pct_plus                  0.1305\
        \     0.005    23.956     0.000             \nst_pred_built_out_sf       \
        \                 -0.0369     0.006    -6.627     0.000             \nst_pred_rich_owned_antique\
        \                   0.0210     0.003     6.332     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0915     0.012    -7.498     0.000             \nst_tracts_income_segment_6_hh\
        \                0.1763     0.010    17.205     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1078     0.011     9.616     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.3201     0.071     4.531     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0515     0.019    -2.690     0.007             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.1394     0.052     2.686     0.007             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.0440     0.043    -1.022     0.307             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.1157     0.083    -1.401     0.161             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.6278     0.057   -11.001     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.6338     0.094     6.751     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           1.0920     0.036    30.644     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -1.3369     0.075   -17.814     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
