modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.354027495470668
    - 0.6599965689480249
    - 0.025979234602712724
    - 0.2525091655109701
    - -0.4193104196409538
    - 1.6436684220673083
    - 0.2262221244637075
    - 0.24439222457621096
    - -0.4683270672264933
    - -0.3344817998050789
    - 0.168219438564966
    - -0.04762043159199305
    - -0.013826307504117718
    - 0.035538881649869083
    - 0.08607976870467834
    - 0.11100680457388021
    - -1.2281779711509848
    - -0.29464557705504113
    - 0.8946698607406424
    - 1.9847910662517623
    - -2.5953183609307904
    - -0.002251904650414514
    - -0.6390228915391619
    - -1.3020755755817262
    - 2.885007106774685
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,246\nModel:\
        \         Multinomial Logit   Df Residuals:              2,221\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.118\nTime:          \
        \            18:01   Pseudo R-bar-squ.:         0.115\nAIC:              \
        \    18,300.585   Log-Likelihood:       -9,125.293\nBIC:                 \
        \ 18,443.508   LL-Null:             -10,343.212\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.3540     0.028    84.506  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6600\
        \     0.030    22.131     0.000             \nst_bg_mean_children        \
        \                  0.0260     0.038     0.678     0.498             \nst_bg_mean_year_built\
        \                        0.2525     0.043     5.918     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.4193     0.048    -8.733\
        \     0.000             \nst_bg_prop_hh_rent                           1.6437\
        \     0.116    14.149     0.000             \nst_bg_prop_units_sf        \
        \                  0.2262     0.043     5.265     0.000             \nst_bg_ratio_households_to_units\
        \              0.2444     0.074     3.323     0.001             \nst_bg_total_units\
        \                           -0.4683     0.082    -5.710     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3345     0.049    -6.820\
        \     0.000             \nst_density_units_90pct_plus                  0.1682\
        \     0.030     5.671     0.000             \nst_pred_built_out_sf       \
        \                 -0.0476     0.056    -0.847     0.397             \nst_pred_rich_owned_antique\
        \                  -0.0138     0.079    -0.176     0.860             \nst_tracts_income_segment_1_hh\
        \                0.0355     0.028     1.257     0.209             \nst_tracts_income_segment_6_hh\
        \                0.0861     0.057     1.519     0.129             \nst_zones_density_units_ave_5_min_sov\
        \         0.1110     0.047     2.340     0.019             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -1.2282     0.477    -2.573     0.010             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.2946     0.180    -1.639     0.101             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.8947     0.406     2.202     0.028             \nst_zones_jobs_2_sum_5_min_sov\
        \                1.9848     0.368     5.390     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \               -2.5953     0.480    -5.402     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.0023     0.360    -0.006     0.995             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.6390     0.695    -0.919     0.358             \nst_zones_total_jobs_sum_20_min_sov\
        \          -1.3021     0.326    -3.996     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          2.8850     0.573     5.039     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
