modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.0741570275424737
    - 0.6126630474119567
    - 0.2097894847868753
    - 0.09253640550153176
    - -0.1713575891511589
    - 1.0225933883283247
    - 0.43114784775207304
    - 0.03129914715047804
    - 0.08343691401694195
    - -0.15784350842993786
    - 0.3162751918265608
    - -0.12553509251567624
    - -0.09803931596170105
    - -0.08147466536261896
    - -0.049445077629330425
    - 0.041569868275907446
    - -1.0626095833569986
    - 0.49271295161067374
    - 0.5493261301678045
    - -0.24186668110415463
    - 0.3981998173908998
    - -1.2910833364675995
    - 1.7469176428311914
    - 0.5542518729411904
    - -1.3709655160425316
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          3,965\nModel:\
        \         Multinomial Logit   Df Residuals:              3,940\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.111\nTime:          \
        \            20:53   Pseudo R-bar-squ.:         0.110\nAIC:              \
        \    32,514.540   Log-Likelihood:      -16,232.270\nBIC:                 \
        \ 32,671.672   LL-Null:             -18,259.500\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.0742     0.020   105.854  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6127\
        \     0.031    19.965     0.000             \nst_bg_mean_children        \
        \                  0.2098     0.036     5.829     0.000             \nst_bg_mean_year_built\
        \                        0.0925     0.041     2.262     0.024            \
        \ \nst_bg_median_value_13_acs                   -0.1714     0.029    -5.991\
        \     0.000             \nst_bg_prop_hh_rent                           1.0226\
        \     0.038    26.642     0.000             \nst_bg_prop_units_sf        \
        \                  0.4311     0.038    11.246     0.000             \nst_bg_ratio_households_to_units\
        \              0.0313     0.047     0.667     0.505             \nst_bg_total_units\
        \                            0.0834     0.044     1.901     0.057        \
        \     \nst_density_jobs_90pct_plus                  -0.1578     0.018    -8.601\
        \     0.000             \nst_density_units_90pct_plus                  0.3163\
        \     0.015    21.677     0.000             \nst_pred_built_out_sf       \
        \                 -0.1255     0.062    -2.037     0.042             \nst_pred_rich_owned_antique\
        \                  -0.0980     0.028    -3.495     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0815     0.034    -2.409     0.016             \nst_tracts_income_segment_6_hh\
        \               -0.0494     0.044    -1.128     0.259             \nst_zones_density_units_ave_5_min_sov\
        \         0.0416     0.026     1.574     0.116             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -1.0626     0.266    -3.994     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.4927     0.103     4.788     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.5493     0.204     2.699     0.007             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.2419     0.161    -1.499     0.134             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.3982     0.336     1.184     0.236             \nst_zones_jobs_4_sum_5_min_sov\
        \               -1.2911     0.221    -5.847     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                1.7469     0.335     5.209     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.5543     0.125     4.441     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -1.3710     0.300    -4.569     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
