modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.4816267727453956
    - 0.5338283098519649
    - 0.08485361947910727
    - 0.0017214171597086558
    - 0.011619020368939612
    - 1.406939881066996
    - -0.08559774350559798
    - 0.28224492833828374
    - 0.09219462039126468
    - -0.11432890435353144
    - 0.4912688663180776
    - -0.17588890817134545
    - -1.8951285862721716
    - -0.036879003764359375
    - -0.7884836189943396
    - -0.12142639411735745
    - -1.5693134833149527
    - -0.16660553903817846
    - -0.12426338221618129
    - 0.44905135778309213
    - -0.9575144146199696
    - 0.5206984760324559
    - 0.3217350608619808
    - 0.20609977147576336
    - 1.25444398881044
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,326\nModel:\
        \         Multinomial Logit   Df Residuals:              1,301\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.281\nTime:          \
        \            21:02   Pseudo R-bar-squ.:         0.276\nAIC:              \
        \     8,836.406   Log-Likelihood:       -4,393.203\nBIC:                 \
        \  8,966.154   LL-Null:              -6,106.456\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.4816     0.036    69.612  \
        \   0.000             \nst_bg_mean_age_of_head                       0.5338\
        \     0.047    11.408     0.000             \nst_bg_mean_children        \
        \                  0.0849     0.042     2.034     0.042             \nst_bg_mean_year_built\
        \                        0.0017     0.058     0.030     0.976            \
        \ \nst_bg_median_value_13_acs                    0.0116     0.121     0.096\
        \     0.924             \nst_bg_prop_hh_rent                           1.4069\
        \     0.064    21.966     0.000             \nst_bg_prop_units_sf        \
        \                 -0.0856     0.049    -1.742     0.081             \nst_bg_ratio_households_to_units\
        \              0.2822     0.075     3.776     0.000             \nst_bg_total_units\
        \                            0.0922     0.086     1.078     0.281        \
        \     \nst_density_jobs_90pct_plus                  -0.1143     0.067    -1.703\
        \     0.089             \nst_density_units_90pct_plus                  0.4913\
        \     0.024    20.379     0.000             \nst_pred_built_out_sf       \
        \                 -0.1759     0.127    -1.388     0.165             \nst_pred_rich_owned_antique\
        \                  -1.8951     2.425    -0.781     0.435             \nst_tracts_income_segment_1_hh\
        \               -0.0369     0.038    -0.970     0.332             \nst_tracts_income_segment_6_hh\
        \               -0.7885     0.230    -3.432     0.001             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1214     0.086    -1.411     0.158             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -1.5693     0.458    -3.423     0.001             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1666     0.167    -0.999     0.318             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.1243     0.376    -0.331     0.741             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.4491     0.379     1.185     0.236             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.9575     0.489    -1.960     0.050             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.5207     0.410     1.269     0.204             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.3217     0.807     0.399     0.690             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.2061     0.603     0.342     0.732             \nst_zones_total_units_sum_10_min_sov\
        \          1.2544     0.776     1.616     0.106             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
