modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.347205369223295
    - 0.6612171821477318
    - -0.1475610150291698
    - 0.13194401637803216
    - -0.34018355637075354
    - 1.151002926233273
    - 0.22534897260946127
    - 0.574572151756462
    - -0.04532249717316456
    - -0.08872871297366774
    - 0.3137707992706835
    - -0.18798579431201787
    - -1.897467889388927
    - -0.014416157020713692
    - -1.0874426085334736
    - -0.29901846806556354
    - 0.6007370239646412
    - 0.8577105091053941
    - -0.2020804628621022
    - 1.047311751959831
    - 0.46163025353228143
    - 2.0188732520982566
    - -6.159947321907864
    - 0.9336522099690905
    - 0.6278077498984418
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,237\nModel:\
        \         Multinomial Logit   Df Residuals:              1,212\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.177\nTime:          \
        \            18:00   Pseudo R-bar-squ.:         0.172\nAIC:              \
        \     9,430.300   Log-Likelihood:       -4,690.150\nBIC:                 \
        \  9,558.312   LL-Null:              -5,696.596\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.3472     0.039    59.603  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6612\
        \     0.048    13.905     0.000             \nst_bg_mean_children        \
        \                 -0.1476     0.048    -3.083     0.002             \nst_bg_mean_year_built\
        \                        0.1319     0.059     2.244     0.025            \
        \ \nst_bg_median_value_13_acs                   -0.3402     0.123    -2.773\
        \     0.006             \nst_bg_prop_hh_rent                           1.1510\
        \     0.076    15.194     0.000             \nst_bg_prop_units_sf        \
        \                  0.2253     0.056     4.053     0.000             \nst_bg_ratio_households_to_units\
        \              0.5746     0.107     5.386     0.000             \nst_bg_total_units\
        \                           -0.0453     0.081    -0.561     0.575        \
        \     \nst_density_jobs_90pct_plus                  -0.0887     0.074    -1.205\
        \     0.228             \nst_density_units_90pct_plus                  0.3138\
        \     0.035     9.072     0.000             \nst_pred_built_out_sf       \
        \                 -0.1880     0.125    -1.504     0.133             \nst_pred_rich_owned_antique\
        \                  -1.8975     2.300    -0.825     0.409             \nst_tracts_income_segment_1_hh\
        \               -0.0144     0.034    -0.425     0.671             \nst_tracts_income_segment_6_hh\
        \               -1.0874     0.216    -5.041     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.2990     0.092    -3.267     0.001             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.6007     0.489     1.228     0.219             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.8577     0.174     4.940     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.2021     0.393    -0.514     0.607             \nst_zones_jobs_2_sum_5_min_sov\
        \                1.0473     0.394     2.659     0.008             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.4616     0.509     0.907     0.364             \nst_zones_jobs_4_sum_5_min_sov\
        \                2.0189     0.446     4.525     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -6.1599     0.850    -7.245     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.9337     0.618     1.511     0.131             \nst_zones_total_units_sum_10_min_sov\
        \          0.6278     0.807     0.778     0.436             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
