modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.4267658739488525
    - 0.3280205681112604
    - 0.32776262750008506
    - 0.05210594235692822
    - 0.18958925516053118
    - 1.0206345195719202
    - 0.1183551519455428
    - 0.31031906785254415
    - 0.018233320043851527
    - -0.36543428672696426
    - 0.19626017823968855
    - 0.0006574237486539784
    - -0.1844467676590503
    - 0.16340615495912028
    - -0.03883336412150535
    - -0.30503463403889947
    - -1.7017263493557677
    - 0.5924988403020951
    - -0.37779119271904177
    - 0.26789550048431987
    - 0.24092194596237543
    - 0.1699746614257491
    - -0.9802148635128989
    - -0.2684520442390448
    - 2.376773685210958
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          5,857\nModel:\
        \         Multinomial Logit   Df Residuals:              5,832\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.153\nTime:          \
        \            20:20   Pseudo R-bar-squ.:         0.152\nAIC:              \
        \    45,739.010   Log-Likelihood:      -22,844.505\nBIC:                 \
        \ 45,905.895   LL-Null:             -26,972.482\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.4268     0.023   106.813  \
        \   0.000             \nst_bg_mean_age_of_head                       0.3280\
        \     0.031    10.435     0.000             \nst_bg_mean_children        \
        \                  0.3278     0.023    14.473     0.000             \nst_bg_mean_year_built\
        \                        0.0521     0.038     1.366     0.172            \
        \ \nst_bg_median_value_13_acs                    0.1896     0.025     7.452\
        \     0.000             \nst_bg_prop_hh_rent                           1.0206\
        \     0.048    21.388     0.000             \nst_bg_prop_units_sf        \
        \                  0.1184     0.044     2.718     0.007             \nst_bg_ratio_households_to_units\
        \              0.3103     0.045     6.947     0.000             \nst_bg_total_units\
        \                            0.0182     0.058     0.312     0.755        \
        \     \nst_density_jobs_90pct_plus                  -0.3654     0.022   -16.629\
        \     0.000             \nst_density_units_90pct_plus                  0.1963\
        \     0.015    12.888     0.000             \nst_pred_built_out_sf       \
        \                  0.0007     0.017     0.039     0.969             \nst_pred_rich_owned_antique\
        \                  -0.1844     0.111    -1.668     0.095             \nst_tracts_income_segment_1_hh\
        \                0.1634     0.034     4.855     0.000             \nst_tracts_income_segment_6_hh\
        \               -0.0388     0.088    -0.441     0.659             \nst_zones_density_units_ave_5_min_sov\
        \        -0.3050     0.041    -7.506     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -1.7017     0.560    -3.036     0.002             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.5925     0.101     5.843     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.3778     0.300    -1.261     0.207             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.2679     0.258     1.039     0.299             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.2409     0.470     0.513     0.608             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.1700     0.235     0.723     0.470             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.9802     0.435    -2.254     0.024             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.2685     0.295    -0.911     0.362             \nst_zones_total_units_sum_10_min_sov\
        \          2.3768     0.697     3.411     0.001             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
