modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.5488577930262237
    - 0.46126445339514627
    - -0.40809615485598677
    - -0.12578698194455332
    - -0.057761359278623414
    - 0.6118357589814509
    - -0.22795055217843477
    - 0.18103114258204414
    - -0.06639453039345063
    - -0.07455504531116951
    - 0.5558867861760433
    - -0.12971669276054013
    - -0.1591406766607752
    - 0.20400575310775818
    - 0.03547219723860486
    - -0.16675924661188707
    - 1.1288917353277979
    - -0.19023476453590416
    - -0.7827237506281801
    - 0.06983884684742676
    - 0.13831251826260077
    - 0.7139033396505748
    - -0.028886545071019103
    - 0.49076253967935235
    - -1.3810279510307115
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          5,158\nModel:\
        \         Multinomial Logit   Df Residuals:              5,133\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.251\nTime:          \
        \            19:57   Pseudo R-bar-squ.:         0.249\nAIC:              \
        \    35,654.007   Log-Likelihood:      -17,802.003\nBIC:                 \
        \ 35,817.714   LL-Null:             -23,753.468\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.5489     0.017   151.435  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4613\
        \     0.030    15.501     0.000             \nst_bg_mean_children        \
        \                 -0.4081     0.026   -15.663     0.000             \nst_bg_mean_year_built\
        \                       -0.1258     0.035    -3.554     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.0578     0.029    -2.020\
        \     0.043             \nst_bg_prop_hh_rent                           0.6118\
        \     0.017    35.938     0.000             \nst_bg_prop_units_sf        \
        \                 -0.2280     0.025    -9.278     0.000             \nst_bg_ratio_households_to_units\
        \              0.1810     0.056     3.244     0.001             \nst_bg_total_units\
        \                           -0.0664     0.051    -1.311     0.190        \
        \     \nst_density_jobs_90pct_plus                  -0.0746     0.014    -5.171\
        \     0.000             \nst_density_units_90pct_plus                  0.5559\
        \     0.010    54.760     0.000             \nst_pred_built_out_sf       \
        \                 -0.1297     0.026    -5.061     0.000             \nst_pred_rich_owned_antique\
        \                  -0.1591     0.025    -6.470     0.000             \nst_tracts_income_segment_1_hh\
        \                0.2040     0.034     6.067     0.000             \nst_tracts_income_segment_6_hh\
        \                0.0355     0.027     1.298     0.194             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1668     0.032    -5.276     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          1.1289     0.183     6.172     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1902     0.059    -3.200     0.001             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.7827     0.141    -5.548     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.0698     0.122     0.570     0.568             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.1383     0.229     0.604     0.546             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.7139     0.156     4.581     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.0289     0.237    -0.122     0.903             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.4908     0.092     5.332     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -1.3810     0.203    -6.805     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
