modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.094609344361909
    - 0.5440262824782558
    - 0.2133514697714852
    - -0.06655961207072512
    - 0.33070950883108147
    - 0.9347184271176433
    - 0.09078764327957552
    - 0.29573418477519725
    - 0.15751695911148467
    - -0.25822433762345853
    - 0.2302290680677156
    - -0.14079579155654418
    - -1.8144814159099245
    - 0.20951885052896754
    - -0.0656404795014416
    - -0.2584720802163856
    - -3.3210726488718296
    - 0.13539062672032007
    - -0.5932011727442432
    - 0.3649379931913949
    - 0.13042863360035148
    - -0.43023144743374697
    - -0.3608986811089901
    - 1.7843852721950675
    - 2.7697074787862594
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,734\nModel:\
        \         Multinomial Logit   Df Residuals:              1,709\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.122\nTime:          \
        \            20:54   Pseudo R-bar-squ.:         0.119\nAIC:              \
        \    14,077.123   Log-Likelihood:       -7,013.561\nBIC:                 \
        \ 14,213.577   LL-Null:              -7,985.365\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.0946     0.033    64.107  \
        \   0.000             \nst_bg_mean_age_of_head                       0.5440\
        \     0.057     9.551     0.000             \nst_bg_mean_children        \
        \                  0.2134     0.045     4.692     0.000             \nst_bg_mean_year_built\
        \                       -0.0666     0.065    -1.023     0.306            \
        \ \nst_bg_median_value_13_acs                    0.3307     0.043     7.639\
        \     0.000             \nst_bg_prop_hh_rent                           0.9347\
        \     0.081    11.510     0.000             \nst_bg_prop_units_sf        \
        \                  0.0908     0.072     1.266     0.205             \nst_bg_ratio_households_to_units\
        \              0.2957     0.077     3.859     0.000             \nst_bg_total_units\
        \                            0.1575     0.103     1.523     0.128        \
        \     \nst_density_jobs_90pct_plus                  -0.2582     0.037    -6.985\
        \     0.000             \nst_density_units_90pct_plus                  0.2302\
        \     0.027     8.549     0.000             \nst_pred_built_out_sf       \
        \                 -0.1408     0.046    -3.093     0.002             \nst_pred_rich_owned_antique\
        \                  -1.8145     4.159    -0.436     0.663             \nst_tracts_income_segment_1_hh\
        \                0.2095     0.065     3.220     0.001             \nst_tracts_income_segment_6_hh\
        \               -0.0656     0.155    -0.423     0.672             \nst_zones_density_units_ave_5_min_sov\
        \        -0.2585     0.073    -3.520     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -3.3211     0.986    -3.367     0.001             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.1354     0.252     0.538     0.590             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.5932     0.613    -0.967     0.333             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.3649     0.516     0.708     0.479             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.1304     0.882     0.148     0.882             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.4302     0.518    -0.831     0.406             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.3609     0.811    -0.445     0.656             \nst_zones_total_jobs_sum_20_min_sov\
        \           1.7844     1.104     1.616     0.106             \nst_zones_total_units_sum_10_min_sov\
        \          2.7697     1.228     2.255     0.024             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
