modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.526026101167557
    - 0.43493435628414323
    - 0.06415395608683867
    - 0.21943112687119495
    - -0.16544676955966664
    - 0.418626014743058
    - 0.2586759383439598
    - 0.5327645703737732
    - 0.09967641428200359
    - -0.47754402117969325
    - 0.10672732274493352
    - -0.07514865269318208
    - 0.07121325925450239
    - -0.3726876886988237
    - 0.24154230680094363
    - -0.08709907464046945
    - -0.5252048217514435
    - 0.06616868551223731
    - -0.6143359120795817
    - -0.6380254534472972
    - 1.9866306340868958
    - -0.7141626665932579
    - 0.3597551053585284
    - -0.5569410749055118
    - 0.6434639937948903
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          54,953\nModel:\
        \         Multinomial Logit   Df Residuals:              54,928\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.099\nTime:       \
        \               18:38   Pseudo R-bar-squ.:          0.098\nAIC:          \
        \       456,316.248   Log-Likelihood:      -228,133.124\nBIC:            \
        \     456,539.104   LL-Null:             -253,067.917\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.5260     0.007   353.792  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4349\
        \     0.010    45.361     0.000             \nst_bg_mean_children        \
        \                  0.0642     0.006     9.965     0.000             \nst_bg_mean_year_built\
        \                        0.2194     0.008    26.197     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.1654     0.008   -19.587\
        \     0.000             \nst_bg_prop_hh_rent                           0.4186\
        \     0.011    39.337     0.000             \nst_bg_prop_units_sf        \
        \                  0.2587     0.009    28.545     0.000             \nst_bg_ratio_households_to_units\
        \              0.5328     0.014    37.625     0.000             \nst_bg_total_units\
        \                            0.0997     0.008    12.464     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.4775     0.009   -51.894\
        \     0.000             \nst_density_units_90pct_plus                  0.1067\
        \     0.005    21.282     0.000             \nst_pred_built_out_sf       \
        \                 -0.0751     0.006   -13.120     0.000             \nst_pred_rich_owned_antique\
        \                   0.0712     0.005    13.140     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.3727     0.010   -37.866     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2415     0.007    34.912     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0871     0.017    -5.045     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.5252     0.056    -9.418     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.0662     0.017     3.798     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.6143     0.032   -19.411     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.6380     0.035   -18.374     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.9866     0.065    30.394     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.7142     0.058   -12.344     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.3598     0.077     4.684     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.5569     0.028   -19.976     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.6435     0.056    11.465     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
