modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.3624731936779315
    - 0.6238749102534747
    - 0.13973351182130495
    - 0.35605393001902746
    - -0.1039671496775589
    - 1.711490274541496
    - 0.5182334240969266
    - 0.4902780199793109
    - -0.3650193276010543
    - -0.5163045869937485
    - -0.035629541188034575
    - -0.12973140675892944
    - -0.0793522891676818
    - 0.023440428171219486
    - -0.0476174998164951
    - 0.07611910486950892
    - -0.19336312739694161
    - -0.3129672789944419
    - -0.2152936427335097
    - 2.5523036056877095
    - -1.3800016418701246
    - -0.1709766990762288
    - -0.48271966734370836
    - -1.8516269450097025
    - 1.7302810299417164
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          5,182\nModel:\
        \         Multinomial Logit   Df Residuals:              5,157\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.117\nTime:          \
        \            19:30   Pseudo R-bar-squ.:         0.116\nAIC:              \
        \    42,174.548   Log-Likelihood:      -21,062.274\nBIC:                 \
        \ 42,338.372   LL-Null:             -23,863.992\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.3625     0.018   132.715  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6239\
        \     0.020    31.031     0.000             \nst_bg_mean_children        \
        \                  0.1397     0.025     5.529     0.000             \nst_bg_mean_year_built\
        \                        0.3561     0.029    12.300     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.1040     0.030    -3.517\
        \     0.000             \nst_bg_prop_hh_rent                           1.7115\
        \     0.080    21.346     0.000             \nst_bg_prop_units_sf        \
        \                  0.5182     0.030    17.018     0.000             \nst_bg_ratio_households_to_units\
        \              0.4903     0.048    10.128     0.000             \nst_bg_total_units\
        \                           -0.3650     0.049    -7.431     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.5163     0.051   -10.223\
        \     0.000             \nst_density_units_90pct_plus                 -0.0356\
        \     0.030    -1.191     0.234             \nst_pred_built_out_sf       \
        \                 -0.1297     0.051    -2.541     0.011             \nst_pred_rich_owned_antique\
        \                  -0.0794     0.056    -1.429     0.153             \nst_tracts_income_segment_1_hh\
        \                0.0234     0.019     1.222     0.222             \nst_tracts_income_segment_6_hh\
        \               -0.0476     0.037    -1.295     0.195             \nst_zones_density_units_ave_5_min_sov\
        \         0.0761     0.030     2.577     0.010             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.1934     0.316    -0.613     0.540             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.3130     0.111    -2.816     0.005             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.2153     0.253    -0.851     0.395             \nst_zones_jobs_2_sum_5_min_sov\
        \                2.5523     0.230    11.097     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \               -1.3800     0.314    -4.391     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.1710     0.238    -0.718     0.473             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.4827     0.465    -1.039     0.299             \nst_zones_total_jobs_sum_20_min_sov\
        \          -1.8516     0.214    -8.655     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          1.7303     0.379     4.569     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
