modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.487294234920813
    - 0.600014661140477
    - -0.2751714313617372
    - -0.10862498107277513
    - -0.20666672142414103
    - 0.4988020630156412
    - 0.1465964626631495
    - 0.1873359674090159
    - 0.05429825175599734
    - -0.4426517872967495
    - 0.2674534117810468
    - -0.048307742584334054
    - 0.06438977259326038
    - -0.07727392687572791
    - 0.12882728827639864
    - -0.08111596066557632
    - 0.07446979708195499
    - -0.09921497738156593
    - -0.5868379846586377
    - -0.3219297866435304
    - 1.4358772684263361
    - -0.3601326223537349
    - -0.040944821383528715
    - -0.1573915860371394
    - 0.12945844046438237
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         11,420\nModel:\
        \         Multinomial Logit   Df Residuals:             11,395\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.086\nTime:          \
        \            17:58   Pseudo R-bar-squ.:         0.085\nAIC:              \
        \    96,202.505   Log-Likelihood:      -48,076.253\nBIC:                 \
        \ 96,386.083   LL-Null:             -52,591.044\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.4873     0.012   212.663  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6000\
        \     0.019    32.326     0.000             \nst_bg_mean_children        \
        \                 -0.2752     0.016   -17.700     0.000             \nst_bg_mean_year_built\
        \                       -0.1086     0.020    -5.535     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.2067     0.017   -12.115\
        \     0.000             \nst_bg_prop_hh_rent                           0.4988\
        \     0.022    22.936     0.000             \nst_bg_prop_units_sf        \
        \                  0.1466     0.020     7.462     0.000             \nst_bg_ratio_households_to_units\
        \              0.1873     0.032     5.813     0.000             \nst_bg_total_units\
        \                            0.0543     0.021     2.587     0.010        \
        \     \nst_density_jobs_90pct_plus                  -0.4427     0.017   -26.736\
        \     0.000             \nst_density_units_90pct_plus                  0.2675\
        \     0.009    29.720     0.000             \nst_pred_built_out_sf       \
        \                 -0.0483     0.014    -3.402     0.001             \nst_pred_rich_owned_antique\
        \                   0.0644     0.011     6.085     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0773     0.021    -3.708     0.000             \nst_tracts_income_segment_6_hh\
        \                0.1288     0.015     8.403     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0811     0.029    -2.819     0.005             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.0745     0.114     0.651     0.515             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0992     0.037    -2.648     0.008             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.5868     0.068    -8.625     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.3219     0.075    -4.299     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.4359     0.138    10.436     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.3601     0.126    -2.854     0.004             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.0409     0.165    -0.247     0.805             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.1574     0.060    -2.627     0.009             \nst_zones_total_units_sum_10_min_sov\
        \          0.1295     0.114     1.139     0.255             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
