modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.01868315041065216
  - -0.011236167512834072
  - 0.1293841153383255
  - -0.12658704817295074
  - -0.03357592225074768
  - 0.11562193930149078
  - 0.2431359440088272
  - 0.012364501133561134
  - -0.1216338723897934
  - 0.5595651268959045
  - -0.006701626814901829
  - 0.21678893268108368
  - 0.06478911638259888
  - -0.275286465883255
  - -0.5598821640014648
  - 1.3053251504898071
  - -0.0013176845386624336
  - -3.4557313919067383
  - 0.7348765730857849
  - -0.9380190968513489
  - 2.4677932262420654
  - 1.267029881477356
  - 0.3375532031059265
  - -0.6912619471549988
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: hlcm_06001_blocks_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
