modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.5253886642870222
    - -0.03330309998752388
    - 0.20626782647702832
    - -0.08459653417269375
    - -0.040402001672702796
    - 0.4233670987938337
    - -0.17915479619026553
    - 0.2924930119129048
    - 0.270144009708066
    - -0.018323881839502166
    - 0.7216851968252939
    - 0.02975703192211988
    - -0.04652173992185511
    - -0.014695877813878185
    - 0.07649583927357938
    - -0.13888992078072118
    - 0.05585887389274132
    - -0.15405194764615263
    - 0.3693305417465581
    - -0.05677364394030511
    - -0.6953689639892044
    - -0.5804681938446252
    - 0.6625788386549792
    - -0.24852336076016565
    - 0.3156815636534598
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          64,938\nModel:\
        \         Multinomial Logit   Df Residuals:              64,913\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.157\nTime:       \
        \               20:25   Pseudo R-bar-squ.:          0.157\nAIC:          \
        \       504,327.453   Log-Likelihood:      -252,138.727\nBIC:            \
        \     504,554.483   LL-Null:             -299,050.542\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.5254     0.006   420.209  \
        \   0.000             \nst_bg_mean_age_of_head                      -0.0333\
        \     0.008    -4.306     0.000             \nst_bg_mean_children        \
        \                  0.2063     0.007    28.106     0.000             \nst_bg_mean_year_built\
        \                       -0.0846     0.007   -12.629     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.0404     0.007    -5.528\
        \     0.000             \nst_bg_prop_hh_rent                           0.4234\
        \     0.008    55.893     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1792     0.012   -14.991     0.000             \nst_bg_ratio_households_to_units\
        \              0.2925     0.016    18.015     0.000             \nst_bg_total_units\
        \                            0.2701     0.009    28.929     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.0183     0.003    -5.544\
        \     0.000             \nst_density_units_90pct_plus                  0.7217\
        \     0.004   165.081     0.000             \nst_pred_built_out_sf       \
        \                  0.0298     0.006     4.615     0.000             \nst_pred_rich_owned_antique\
        \                  -0.0465     0.011    -4.419     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0147     0.005    -2.712     0.007             \nst_tracts_income_segment_6_hh\
        \                0.0765     0.005    15.996     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1389     0.006   -21.520     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.0559     0.084     0.664     0.507             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1541     0.018    -8.673     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.3693     0.041     8.980     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.0568     0.033    -1.733     0.083             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.6954     0.067   -10.308     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.5805     0.035   -16.478     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.6626     0.070     9.406     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.2485     0.029    -8.522     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.3157     0.095     3.338     0.001             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
