modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.1276122395980055
    - 0.39560608339751024
    - 0.23867383242873175
    - 0.09315080055405206
    - -0.18874846395486533
    - 1.0234671425218267
    - 0.44971076063632737
    - 0.24103823090403012
    - 0.2770439414304879
    - -0.18382232055841402
    - 0.3776422445980963
    - -0.3186128689376972
    - -0.09634056093848294
    - -0.22279724799038841
    - 0.021824979674807937
    - 0.03004046523412269
    - -0.6234079358730488
    - 0.5810444527029602
    - 0.30577556746458895
    - -0.13396590878193032
    - -0.6079847410079269
    - -0.8627694531666662
    - 1.477583924099683
    - 0.4138661249672897
    - -0.7533147712171332
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         11,015\nModel:\
        \         Multinomial Logit   Df Residuals:             10,990\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.148\nTime:          \
        \            20:19   Pseudo R-bar-squ.:         0.147\nAIC:              \
        \    86,527.080   Log-Likelihood:      -43,238.540\nBIC:                 \
        \ 86,709.756   LL-Null:             -50,725.950\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.1276     0.014   149.127  \
        \   0.000             \nst_bg_mean_age_of_head                       0.3956\
        \     0.019    20.801     0.000             \nst_bg_mean_children        \
        \                  0.2387     0.019    12.815     0.000             \nst_bg_mean_year_built\
        \                        0.0932     0.025     3.682     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.1887     0.018   -10.552\
        \     0.000             \nst_bg_prop_hh_rent                           1.0235\
        \     0.025    40.837     0.000             \nst_bg_prop_units_sf        \
        \                  0.4497     0.025    17.997     0.000             \nst_bg_ratio_households_to_units\
        \              0.2410     0.030     7.994     0.000             \nst_bg_total_units\
        \                            0.2770     0.026    10.510     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1838     0.011   -17.143\
        \     0.000             \nst_density_units_90pct_plus                  0.3776\
        \     0.009    43.034     0.000             \nst_pred_built_out_sf       \
        \                 -0.3186     0.085    -3.737     0.000             \nst_pred_rich_owned_antique\
        \                  -0.0963     0.017    -5.772     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.2228     0.021   -10.456     0.000             \nst_tracts_income_segment_6_hh\
        \                0.0218     0.029     0.756     0.450             \nst_zones_density_units_ave_5_min_sov\
        \         0.0300     0.017     1.720     0.085             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.6234     0.164    -3.791     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.5810     0.068     8.507     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.3058     0.125     2.440     0.015             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.1340     0.100    -1.334     0.182             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.6080     0.197    -3.083     0.002             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.8628     0.135    -6.393     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                1.4776     0.199     7.429     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.4139     0.082     5.037     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -0.7533     0.187    -4.023     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
