modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==7)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.671811914866071
    - 0.2596104345474302
    - 0.19687719819521798
    - 0.19123328567386652
    - -0.11687729172907697
    - 2.8522653174826273
    - 0.184879005330738
    - 0.561178778567678
    - -0.4403377644149876
    - -0.3427640989294656
    - 0.4261041997136399
    - -0.07977644447434735
    - -2.120927068223871
    - -0.02398711116414446
    - -0.1888545381810103
    - 0.24587844716950785
    - 1.249011712975822
    - -0.16799328188252352
    - 0.05251017684499995
    - 2.6250616256943884
    - 0.5714972130476977
    - 0.5268568499403646
    - -3.547533072665804
    - -0.060628383737683325
    - -1.5903315327383276
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_rent_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==7)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          4,387\nModel:\
        \         Multinomial Logit   Df Residuals:              4,362\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.239\nTime:          \
        \            20:47   Pseudo R-bar-squ.:         0.238\nAIC:              \
        \    30,791.857   Log-Likelihood:      -15,370.929\nBIC:                 \
        \ 30,951.517   LL-Null:             -20,202.882\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.6718     0.030    89.321  \
        \   0.000             \nst_bg_mean_age_of_head                       0.2596\
        \     0.026    10.112     0.000             \nst_bg_mean_children        \
        \                  0.1969     0.022     8.919     0.000             \nst_bg_mean_year_built\
        \                        0.1912     0.034     5.688     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.1169     0.037    -3.126\
        \     0.002             \nst_bg_prop_hh_rent                           2.8523\
        \     0.086    33.326     0.000             \nst_bg_prop_units_sf        \
        \                  0.1849     0.032     5.788     0.000             \nst_bg_ratio_households_to_units\
        \              0.5612     0.061     9.243     0.000             \nst_bg_total_units\
        \                           -0.4403     0.062    -7.133     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3428     0.030   -11.384\
        \     0.000             \nst_density_units_90pct_plus                  0.4261\
        \     0.014    31.257     0.000             \nst_pred_built_out_sf       \
        \                 -0.0798     0.047    -1.689     0.091             \nst_pred_rich_owned_antique\
        \                  -2.1209     1.171    -1.810     0.070             \nst_tracts_income_segment_1_hh\
        \               -0.0240     0.025    -0.941     0.347             \nst_tracts_income_segment_6_hh\
        \               -0.1889     0.058    -3.278     0.001             \nst_zones_density_units_ave_5_min_sov\
        \         0.2459     0.033     7.476     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          1.2490     0.355     3.520     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1680     0.115    -1.467     0.142             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.0525     0.285     0.184     0.854             \nst_zones_jobs_2_sum_5_min_sov\
        \                2.6251     0.254    10.339     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.5715     0.401     1.427     0.154             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.5269     0.282     1.866     0.062             \nst_zones_jobs_5_sum_5_min_sov\
        \               -3.5475     0.510    -6.953     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.0606     0.380    -0.159     0.873             \nst_zones_total_units_sum_10_min_sov\
        \         -1.5903     0.453    -3.514     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
