modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06001")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06001") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 3.0601299171237817
    - 0.5467838983631186
    - 0.08801187586755457
    - 0.04144377302686693
    - -0.10028642065512473
    - 0.8066677652535483
    - 0.14757325086227147
    - 0.4130662693996088
    - 0.17121318367472002
    - -0.18302153693979836
    - 0.5508486265764191
    - -0.17809529086395803
    - -0.05386615244146156
    - -0.028992111944240756
    - -0.15646024282407842
    - -0.14765712015321877
    - 0.35327753538197965
    - 0.025715835639450606
    - -0.32169677222869403
    - 0.1789318055741698
    - 1.0594969856282352
    - -0.9024819864610372
    - 0.07772487180171185
    - -0.0633418172534
    - -0.6556185984732796
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06001_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         17,458\nModel:\
        \         Multinomial Logit   Df Residuals:             17,433\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.215\nTime:          \
        \            20:49   Pseudo R-bar-squ.:         0.215\nAIC:              \
        \   126,211.839   Log-Likelihood:      -63,080.920\nBIC:                 126,406.028\
        \   LL-Null:             -80,397.061\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    3.0601     0.008   387.679  \
        \   0.000             \nst_bg_mean_age_of_head                       0.5468\
        \     0.013    42.096     0.000             \nst_bg_mean_children        \
        \                  0.0880     0.010     8.384     0.000             \nst_bg_mean_year_built\
        \                        0.0414     0.013     3.088     0.002            \
        \ \nst_bg_median_value_13_acs                   -0.1003     0.017    -5.881\
        \     0.000             \nst_bg_prop_hh_rent                           0.8067\
        \     0.016    51.553     0.000             \nst_bg_prop_units_sf        \
        \                  0.1476     0.015     9.912     0.000             \nst_bg_ratio_households_to_units\
        \              0.4131     0.020    21.122     0.000             \nst_bg_total_units\
        \                            0.1712     0.020     8.391     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1830     0.010   -18.909\
        \     0.000             \nst_density_units_90pct_plus                  0.5508\
        \     0.006    97.159     0.000             \nst_pred_built_out_sf       \
        \                 -0.1781     0.017   -10.450     0.000             \nst_pred_rich_owned_antique\
        \                  -0.0539     0.013    -4.268     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0290     0.014    -2.107     0.035             \nst_tracts_income_segment_6_hh\
        \               -0.1565     0.023    -6.659     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1477     0.018    -7.990     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.3533     0.088     4.003     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.0257     0.028     0.908     0.364             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.3217     0.065    -4.938     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.1789     0.062     2.880     0.004             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.0595     0.092    11.472     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.9025     0.085   -10.562     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.0777     0.135     0.574     0.566             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.0633     0.052    -1.208     0.227             \nst_zones_total_units_sum_10_min_sov\
        \         -0.6556     0.104    -6.296     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
