modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06081")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06081") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.308367991497194
    - 0.4108184381129379
    - -0.4928069521654841
    - 0.2939574890603795
    - -0.6698574888910217
    - 0.22201715500930017
    - 0.20834911847669982
    - 0.5594481585389921
    - 0.403512217568792
    - -0.25207436541414896
    - 0.26133431871116297
    - -0.05645601580957782
    - 0.004197355003971786
    - -0.27020987221155224
    - 0.4411842650840086
    - 0.3714756812040883
    - 0.5536301007637128
    - -0.05081285810351839
    - 0.4510086300550116
    - 0.006099496176432259
    - -0.004093683706407569
    - -1.8624698469473933
    - 1.9321023100837793
    - 2.231114405463652
    - -2.93478153250522
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum +  + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06081_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081") & (zone_id
        == zone_id) & (zone_id == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,912\nModel:\
        \         Multinomial Logit   Df Residuals:              2,887\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.136\nTime:          \
        \            17:43   Pseudo R-bar-squ.:         0.134\nAIC:              \
        \    23,223.280   Log-Likelihood:      -11,586.640\nBIC:                 \
        \ 23,372.695   LL-Null:             -13,410.256\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.3084     0.026    90.438  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4108\
        \     0.044     9.328     0.000             \nst_bg_mean_children        \
        \                 -0.4928     0.034   -14.301     0.000             \nst_bg_mean_year_built\
        \                        0.2940     0.042     7.071     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.6699     0.040   -16.786\
        \     0.000             \nst_bg_prop_hh_rent                           0.2220\
        \     0.030     7.339     0.000             \nst_bg_prop_units_sf        \
        \                  0.2083     0.035     5.975     0.000             \nst_bg_ratio_households_to_units\
        \              0.5594     0.079     7.118     0.000             \nst_bg_total_units\
        \                            0.4035     0.071     5.692     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.2521     0.026    -9.616\
        \     0.000             \nst_density_units_90pct_plus                  0.2613\
        \     0.016    16.408     0.000             \nst_pred_built_out_sf       \
        \                 -0.0565     0.020    -2.843     0.004             \nst_pred_rich_owned_antique\
        \                   0.0042     0.015     0.283     0.777             \nst_tracts_income_segment_1_hh\
        \               -0.2702     0.043    -6.222     0.000             \nst_tracts_income_segment_6_hh\
        \                0.4412     0.035    12.559     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.3715     0.040     9.289     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.5536     0.246     2.251     0.024             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0508     0.067    -0.758     0.448             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.4510     0.188     2.404     0.016             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.0061     0.152     0.040     0.968             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.0041     0.310    -0.013     0.989             \nst_zones_jobs_4_sum_5_min_sov\
        \               -1.8625     0.216    -8.622     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                1.9321     0.341     5.667     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           2.2311     0.118    18.950     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -2.9348     0.249   -11.793     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
