modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.112458195372909
    - -0.16796237113267987
    - -0.39829079509255594
    - -0.17275959746537947
    - 0.012048380113986219
    - 0.3801544585135704
    - -0.15011284738785774
    - -0.01849188096665432
    - 0.38996855114712276
    - 0.010091905529322756
    - 0.8648020543883673
    - 0.06700184607289997
    - -0.12481192442593392
    - 0.0703192907717273
    - 0.03473502116365096
    - -0.07494712010642672
    - 1.1550936152217095
    - -0.13176886058308476
    - 0.07823152336980263
    - 0.08965239289723118
    - 0.5596605276281295
    - -0.10704063951399481
    - -0.49173587751899595
    - 0.1095957966967383
    - -1.6559491024689137
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          36,829\nModel:\
        \         Multinomial Logit   Df Residuals:              36,804\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.231\nTime:       \
        \               19:39   Pseudo R-bar-squ.:          0.231\nAIC:          \
        \       261,004.527   Log-Likelihood:      -130,477.264\nBIC:            \
        \     261,217.378   LL-Null:             -169,603.813\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.1125     0.006   367.034  \
        \   0.000             \nst_bg_mean_age_of_head                      -0.1680\
        \     0.010   -17.370     0.000             \nst_bg_mean_children        \
        \                 -0.3983     0.013   -30.025     0.000             \nst_bg_mean_year_built\
        \                       -0.1728     0.008   -20.723     0.000            \
        \ \nst_bg_median_value_13_acs                    0.0120     0.009     1.293\
        \     0.196             \nst_bg_prop_hh_rent                           0.3802\
        \     0.011    35.412     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1501     0.018    -8.120     0.000             \nst_bg_ratio_households_to_units\
        \             -0.0185     0.021    -0.866     0.387             \nst_bg_total_units\
        \                            0.3900     0.012    33.393     0.000        \
        \     \nst_density_jobs_90pct_plus                   0.0101     0.004    \
        \ 2.433     0.015             \nst_density_units_90pct_plus              \
        \    0.8648     0.007   120.571     0.000             \nst_pred_built_out_sf\
        \                         0.0670     0.013     4.975     0.000           \
        \  \nst_pred_rich_owned_antique                  -0.1248     0.028    -4.501\
        \     0.000             \nst_tracts_income_segment_1_hh                0.0703\
        \     0.007    10.674     0.000             \nst_tracts_income_segment_6_hh\
        \                0.0347     0.006     5.992     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0749     0.008    -9.242     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          1.1551     0.119     9.696     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1318     0.025    -5.228     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.0782     0.059     1.319     0.187             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.0897     0.046     1.946     0.052             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.5597     0.099     5.627     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.1070     0.050    -2.149     0.032             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.4917     0.102    -4.807     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.1096     0.034     3.179     0.001             \nst_zones_total_units_sum_10_min_sov\
        \         -1.6559     0.130   -12.700     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
