modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.494265500288523
    - 0.6334720809194407
    - -0.1162948631530659
    - -0.048266382760006395
    - -0.0705438078160668
    - 3.5109643092592986
    - 0.07785594609327871
    - 0.1940870539850893
    - -0.23227170030666533
    - -0.15053934557814025
    - 0.5453989306206338
    - -2.0921996515282597
    - -1.8593809355599984
    - -0.01345925238555694
    - -0.17768566952903436
    - -0.08899480391488068
    - 1.1468884365342755
    - -0.36557114497692456
    - -1.032314170779792
    - 0.585289998740767
    - 1.0102711430495155
    - -1.141762006621912
    - 0.745243804829316
    - 1.1539531917771917
    - -2.3056246523981483
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,277\nModel:\
        \         Multinomial Logit   Df Residuals:              1,252\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.253\nTime:          \
        \            20:01   Pseudo R-bar-squ.:         0.249\nAIC:              \
        \     8,835.012   Log-Likelihood:       -4,392.506\nBIC:                 \
        \  8,963.819   LL-Null:              -5,880.802\n====================================================================================================\n\
        \                                               coef         std err     \
        \    z     P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.4943           0.038    65.432\
        \     0.000             \nst_bg_mean_age_of_head                       0.6335\
        \           0.046    13.819     0.000             \nst_bg_mean_children  \
        \                       -0.1163           0.049    -2.350     0.019      \
        \       \nst_bg_mean_year_built                       -0.0483           0.063\
        \    -0.766     0.444             \nst_bg_median_value_13_acs            \
        \       -0.0705           0.065    -1.081     0.280             \nst_bg_prop_hh_rent\
        \                           3.5110           0.164    21.424     0.000   \
        \          \nst_bg_prop_units_sf                          0.0779         \
        \  0.062     1.259     0.208             \nst_bg_ratio_households_to_units\
        \              0.1941           0.114     1.703     0.089             \nst_bg_total_units\
        \                           -0.2323           0.140    -1.658     0.097  \
        \           \nst_density_jobs_90pct_plus                  -0.1505        \
        \   0.039    -3.887     0.000             \nst_density_units_90pct_plus  \
        \                0.5454           0.024    22.734     0.000             \n\
        st_pred_built_out_sf                        -2.0922   4,292,362.737    -0.000\
        \     1.000             \nst_pred_rich_owned_antique                  -1.8594\
        \   4,809,442.242    -0.000     1.000             \nst_tracts_income_segment_1_hh\
        \               -0.0135           0.046    -0.292     0.771             \n\
        st_tracts_income_segment_6_hh               -0.1777           0.088    -2.014\
        \     0.044             \nst_zones_density_units_ave_5_min_sov        -0.0890\
        \           0.064    -1.394     0.163             \nst_zones_income_6_hh_sum_10_min_sov\
        \          1.1469           0.694     1.653     0.098             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.3656           0.246    -1.485     0.137             \n\
        st_zones_jobs_1_sum_5_min_sov               -1.0323           0.559    -1.846\
        \     0.065             \nst_zones_jobs_2_sum_5_min_sov                0.5853\
        \           0.508     1.152     0.249             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.0103           0.817     1.237     0.216             \n\
        st_zones_jobs_4_sum_5_min_sov               -1.1418           0.555    -2.059\
        \     0.040             \nst_zones_jobs_5_sum_5_min_sov                0.7452\
        \           0.968     0.770     0.441             \nst_zones_total_jobs_sum_20_min_sov\
        \           1.1540           0.745     1.549     0.121             \nst_zones_total_units_sum_10_min_sov\
        \         -2.3056           0.860    -2.683     0.007             \n===================================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
