modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06001")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06001") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.8182216434995455
    - -0.03161709214484191
    - -0.36374770582934773
    - -0.1155001610438145
    - -0.10412440642849902
    - 0.7317613793485448
    - 0.007957869363459881
    - 0.20736505544546552
    - 0.13988953129578577
    - -0.12712464237113283
    - 0.6465891182124942
    - -0.2676942411646022
    - -0.07213005803965943
    - -0.11471710073084149
    - 0.082217336376748
    - 0.00648932709079767
    - 0.1341798486311821
    - -0.036842409569654004
    - 0.0697289482021272
    - 0.6068214999943257
    - 0.86184240684452
    - -1.0748036258804903
    - -0.04657429639867045
    - -0.5434560393473206
    - -0.2712259797896554
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06001_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06001") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         19,168\nModel:\
        \         Multinomial Logit   Df Residuals:             19,143\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.306\nTime:          \
        \            19:31   Pseudo R-bar-squ.:         0.305\nAIC:              \
        \   122,654.577   Log-Likelihood:      -61,302.288\nBIC:                 122,851.102\
        \   LL-Null:             -88,271.902\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.8182     0.008   339.188  \
        \   0.000             \nst_bg_mean_age_of_head                      -0.0316\
        \     0.011    -2.804     0.005             \nst_bg_mean_children        \
        \                 -0.3637     0.011   -32.117     0.000             \nst_bg_mean_year_built\
        \                       -0.1155     0.013    -9.158     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.1041     0.016    -6.521\
        \     0.000             \nst_bg_prop_hh_rent                           0.7318\
        \     0.016    47.127     0.000             \nst_bg_prop_units_sf        \
        \                  0.0080     0.016     0.502     0.616             \nst_bg_ratio_households_to_units\
        \              0.2074     0.020    10.152     0.000             \nst_bg_total_units\
        \                            0.1399     0.019     7.384     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1271     0.008   -16.070\
        \     0.000             \nst_density_units_90pct_plus                  0.6466\
        \     0.006   113.342     0.000             \nst_pred_built_out_sf       \
        \                 -0.2677     0.024   -11.371     0.000             \nst_pred_rich_owned_antique\
        \                  -0.0721     0.015    -4.679     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.1147     0.013    -9.036     0.000             \nst_tracts_income_segment_6_hh\
        \                0.0822     0.023     3.618     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.0065     0.020     0.332     0.740             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.1342     0.094     1.435     0.151             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.0368     0.027    -1.356     0.175             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.0697     0.064     1.096     0.273             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.6068     0.058    10.485     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.8618     0.090     9.527     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -1.0748     0.084   -12.733     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.0466     0.134    -0.347     0.729             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.5435     0.053   -10.291     0.000             \nst_zones_total_units_sum_10_min_sov\
        \         -0.2712     0.111    -2.451     0.014             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
