modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.9868046860736563
    - 0.23285303242938218
    - -0.19912544476586158
    - -0.006558726265090396
    - -0.14284534785383377
    - 0.7682244703644884
    - -0.15145599490083067
    - 0.11324476739253696
    - 0.14916292498671752
    - -0.07825019430285117
    - 0.6053627800171226
    - -0.2633013472195578
    - -0.14913880605923388
    - -0.19169840264686686
    - 0.2453296360871451
    - 0.11991442550911242
    - -0.7534780704877543
    - 0.24207878725343487
    - -0.24978512653300697
    - -0.2925501708737235
    - 0.9740594733936893
    - 0.002569358950105493
    - -0.6960052792516382
    - -0.0936887405205057
    - 0.7174541043160687
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          6,824\nModel:\
        \         Multinomial Logit   Df Residuals:              6,799\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.306\nTime:          \
        \            19:34   Pseudo R-bar-squ.:         0.306\nAIC:              \
        \    43,641.516   Log-Likelihood:      -21,795.758\nBIC:                 \
        \ 43,812.221   LL-Null:             -31,425.681\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.9868     0.014   212.475  \
        \   0.000             \nst_bg_mean_age_of_head                       0.2329\
        \     0.025     9.336     0.000             \nst_bg_mean_children        \
        \                 -0.1991     0.018   -10.900     0.000             \nst_bg_mean_year_built\
        \                       -0.0066     0.024    -0.275     0.783            \
        \ \nst_bg_median_value_13_acs                   -0.1428     0.028    -5.086\
        \     0.000             \nst_bg_prop_hh_rent                           0.7682\
        \     0.017    44.121     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1515     0.022    -6.985     0.000             \nst_bg_ratio_households_to_units\
        \              0.1132     0.031     3.682     0.000             \nst_bg_total_units\
        \                            0.1492     0.032     4.663     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.0783     0.016    -4.834\
        \     0.000             \nst_density_units_90pct_plus                  0.6054\
        \     0.009    64.526     0.000             \nst_pred_built_out_sf       \
        \                 -0.2633     0.023   -11.336     0.000             \nst_pred_rich_owned_antique\
        \                  -0.1491     0.063    -2.364     0.018             \nst_tracts_income_segment_1_hh\
        \               -0.1917     0.022    -8.558     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2453     0.024    10.034     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1199     0.040     3.014     0.003             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.7535     0.177    -4.268     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.2421     0.048     5.029     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.2498     0.144    -1.736     0.083             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.2926     0.118    -2.472     0.013             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.9741     0.171     5.710     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.0026     0.120     0.021     0.983             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.6960     0.197    -3.528     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.0937     0.100    -0.934     0.350             \nst_zones_total_units_sum_10_min_sov\
        \          0.7175     0.203     3.542     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
