modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06097")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06097") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.4755405863512445
    - 0.6165157973510976
    - 0.15471724912045498
    - 0.04142001303405291
    - 0.30044553614179703
    - 3.044875855875015
    - 0.032117349301883855
    - 0.3862695087833691
    - -0.14992936117420638
    - -0.4468318256605842
    - 0.48807978080946063
    - -0.09893232649139377
    - -2.0306112219051555
    - -0.01741336472354566
    - -0.31821717470003796
    - 0.12869973862255416
    - 1.1332043093617687
    - -0.5540299190884334
    - -1.3418741262978593
    - 2.003796751592485
    - 0.8973231211547152
    - 0.44909909964960754
    - -0.914207478097685
    - -0.12992767495488075
    - -1.8208999789887383
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06097_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06097") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          1,223\nModel:\
        \         Multinomial Logit   Df Residuals:              1,198\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.202\nTime:          \
        \            21:03   Pseudo R-bar-squ.:         0.197\nAIC:              \
        \     9,042.417   Log-Likelihood:       -4,496.208\nBIC:                 \
        \  9,170.143   LL-Null:              -5,632.123\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.4755     0.041    60.917  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6165\
        \     0.047    13.037     0.000             \nst_bg_mean_children        \
        \                  0.1547     0.047     3.299     0.001             \nst_bg_mean_year_built\
        \                        0.0414     0.064     0.645     0.519            \
        \ \nst_bg_median_value_13_acs                    0.3004     0.061     4.890\
        \     0.000             \nst_bg_prop_hh_rent                           3.0449\
        \     0.167    18.230     0.000             \nst_bg_prop_units_sf        \
        \                  0.0321     0.060     0.537     0.591             \nst_bg_ratio_households_to_units\
        \              0.3863     0.109     3.548     0.000             \nst_bg_total_units\
        \                           -0.1499     0.120    -1.246     0.213        \
        \     \nst_density_jobs_90pct_plus                  -0.4468     0.065    -6.867\
        \     0.000             \nst_density_units_90pct_plus                  0.4881\
        \     0.026    18.777     0.000             \nst_pred_built_out_sf       \
        \                 -0.0989     0.125    -0.794     0.427             \nst_pred_rich_owned_antique\
        \                  -2.0306     2.088    -0.972     0.331             \nst_tracts_income_segment_1_hh\
        \               -0.0174     0.044    -0.395     0.693             \nst_tracts_income_segment_6_hh\
        \               -0.3182     0.098    -3.256     0.001             \nst_zones_density_units_ave_5_min_sov\
        \         0.1287     0.062     2.076     0.038             \nst_zones_income_6_hh_sum_10_min_sov\
        \          1.1332     0.644     1.760     0.078             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.5540     0.228    -2.431     0.015             \nst_zones_jobs_1_sum_5_min_sov\
        \               -1.3419     0.494    -2.716     0.007             \nst_zones_jobs_2_sum_5_min_sov\
        \                2.0038     0.440     4.556     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.8973     0.748     1.200     0.230             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.4491     0.509     0.882     0.378             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.9142     0.898    -1.018     0.309             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.1299     0.695    -0.187     0.852             \nst_zones_total_units_sum_10_min_sov\
        \         -1.8209     0.829    -2.197     0.028             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
