modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.241304245650267
    - 0.8117993460204049
    - 0.17891646393794186
    - -0.07909789261776197
    - -0.03379094793425336
    - 0.1853010215485055
    - -0.011883406218187323
    - 0.16258694965459497
    - -0.35166062516727076
    - -0.15413534987564653
    - -0.004948619317263755
    - -0.033954080381278874
    - -0.11425506962430661
    - 0.10810656638352482
    - 0.3656823361216495
    - -0.09530599716394068
    - -0.10234140824599172
    - 0.19888367394845613
    - -0.06772504692997672
    - -0.3390404647969897
    - 1.0816562996504597
    - -0.5736316827777697
    - -0.8766386488478033
    - 0.591083468853197
    - 0.06172526605199582
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,037\nModel:\
        \         Multinomial Logit   Df Residuals:              2,012\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.085\nTime:          \
        \            17:53   Pseudo R-bar-squ.:         0.083\nAIC:              \
        \    17,209.594   Log-Likelihood:       -8,579.797\nBIC:                 \
        \ 17,350.075   LL-Null:              -9,380.732\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.2413     0.030    75.148  \
        \   0.000             \nst_bg_mean_age_of_head                       0.8118\
        \     0.050    16.106     0.000             \nst_bg_mean_children        \
        \                  0.1789     0.044     4.099     0.000             \nst_bg_mean_year_built\
        \                       -0.0791     0.058    -1.362     0.173            \
        \ \nst_bg_median_value_13_acs                   -0.0338     0.038    -0.881\
        \     0.378             \nst_bg_prop_hh_rent                           0.1853\
        \     0.068     2.722     0.006             \nst_bg_prop_units_sf        \
        \                 -0.0119     0.057    -0.207     0.836             \nst_bg_ratio_households_to_units\
        \              0.1626     0.063     2.581     0.010             \nst_bg_total_units\
        \                           -0.3517     0.091    -3.857     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1541     0.046    -3.355\
        \     0.001             \nst_density_units_90pct_plus                 -0.0049\
        \     0.032    -0.154     0.878             \nst_pred_built_out_sf       \
        \                 -0.0340     0.022    -1.557     0.119             \nst_pred_rich_owned_antique\
        \                  -0.1143     0.112    -1.023     0.306             \nst_tracts_income_segment_1_hh\
        \                0.1081     0.052     2.063     0.039             \nst_tracts_income_segment_6_hh\
        \                0.3657     0.128     2.849     0.004             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0953     0.052    -1.836     0.066             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.1023     0.714    -0.143     0.886             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.1989     0.166     1.196     0.232             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.0677     0.446    -0.152     0.879             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.3390     0.378    -0.897     0.370             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.0817     0.706     1.531     0.126             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.5736     0.411    -1.395     0.163             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.8766     0.755    -1.162     0.245             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.5911     0.399     1.480     0.139             \nst_zones_total_units_sum_10_min_sov\
        \          0.0617     1.034     0.060     0.952             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
