modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==2)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 1.8989905085817769
    - 0.7972481335063925
    - 0.003959653085516872
    - -0.023998979610800344
    - -0.4032994021754167
    - 0.30493075249777135
    - 0.2514470254518461
    - 0.028404495661100666
    - 6.534207662991639e-05
    - -0.33817450786157105
    - 0.16389090495051487
    - -0.006336018487642027
    - 0.0477991126418606
    - -0.15552598360849645
    - 0.12783020661573258
    - 0.020853961734843406
    - -0.11985464679104278
    - 0.2968485553655759
    - 0.4486961575753705
    - -0.3894576923448463
    - -1.0162587470106357
    - 0.5795347720209792
    - 0.4109037134712383
    - 0.009223682973862614
    - -0.29026862238376316
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_own_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==2)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,069\nModel:\
        \         Multinomial Logit   Df Residuals:              7,044\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.069\nTime:          \
        \            17:51   Pseudo R-bar-squ.:         0.068\nAIC:              \
        \    60,676.985   Log-Likelihood:      -30,313.493\nBIC:                 \
        \ 60,848.572   LL-Null:             -32,553.948\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    1.8990     0.015   128.552  \
        \   0.000             \nst_bg_mean_age_of_head                       0.7972\
        \     0.024    32.916     0.000             \nst_bg_mean_children        \
        \                  0.0040     0.029     0.135     0.893             \nst_bg_mean_year_built\
        \                       -0.0240     0.032    -0.750     0.453            \
        \ \nst_bg_median_value_13_acs                   -0.4033     0.022   -18.563\
        \     0.000             \nst_bg_prop_hh_rent                           0.3049\
        \     0.030    10.293     0.000             \nst_bg_prop_units_sf        \
        \                  0.2514     0.029     8.701     0.000             \nst_bg_ratio_households_to_units\
        \              0.0284     0.034     0.830     0.407             \nst_bg_total_units\
        \                            0.0001     0.035     0.002     0.999        \
        \     \nst_density_jobs_90pct_plus                  -0.3382     0.020   -17.235\
        \     0.000             \nst_density_units_90pct_plus                  0.1639\
        \     0.015    10.846     0.000             \nst_pred_built_out_sf       \
        \                 -0.0063     0.026    -0.241     0.810             \nst_pred_rich_owned_antique\
        \                   0.0478     0.009     5.540     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.1555     0.024    -6.402     0.000             \nst_tracts_income_segment_6_hh\
        \                0.1278     0.031     4.102     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.0209     0.019     1.122     0.262             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.1199     0.191    -0.628     0.530             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.2968     0.073     4.080     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.4487     0.152     2.951     0.003             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.3895     0.123    -3.161     0.002             \nst_zones_jobs_3_sum_5_min_sov\
        \               -1.0163     0.234    -4.336     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.5795     0.170     3.418     0.001             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.4109     0.247     1.666     0.096             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.0092     0.090     0.103     0.918             \nst_zones_total_units_sum_10_min_sov\
        \         -0.2903     0.231    -1.255     0.210             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
