modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: counties
  choice_column: lcm_county_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.004902099259197712
  - 0.7271050214767456
  - -0.27761003375053406
  - 0.07666714489459991
  max_iter: null
  model_expression: st_mean_home_value + st_total_hh + st_total_jobs + st_total_units
    - 1
  name: hlcm_county_own_1p_55plus_pf
  out_alt_filters: (vacant_residential_units > 0)
  out_alternatives: null
  out_chooser_filters: (lcm_county_id == "-1") & (hh_type==2)
  out_choosers: null
  out_column: lcm_county_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
