modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==6)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.969277849153443
    - 0.6609889983782063
    - -0.14844922439937333
    - -0.09039838157602864
    - -0.11841532267952559
    - 0.8196525842860798
    - -0.13298939932218434
    - -0.043508042190183865
    - -0.00045796451264882155
    - 0.011560654197496814
    - 0.5791059005330725
    - -0.1469852590604726
    - -0.11956190760536614
    - -0.02183558643464905
    - 0.08060242124273527
    - 0.16769035294681123
    - -0.14212478932701905
    - 0.285024910685424
    - 0.46286609946963875
    - -0.4941665088654016
    - 0.21394725280893667
    - 0.4267576415261982
    - -0.776453034523737
    - -0.5916950416501403
    - 0.356655284681151
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_rent_1p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==6)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          7,045\nModel:\
        \         Multinomial Logit   Df Residuals:              7,020\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.250\nTime:          \
        \            19:50   Pseudo R-bar-squ.:         0.249\nAIC:              \
        \    48,714.022   Log-Likelihood:      -24,332.011\nBIC:                 \
        \ 48,885.524   LL-Null:             -32,443.424\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.9693     0.015   201.132  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6610\
        \     0.020    33.567     0.000             \nst_bg_mean_children        \
        \                 -0.1484     0.018    -8.383     0.000             \nst_bg_mean_year_built\
        \                       -0.0904     0.024    -3.811     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.1184     0.028    -4.178\
        \     0.000             \nst_bg_prop_hh_rent                           0.8197\
        \     0.017    49.502     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1330     0.020    -6.531     0.000             \nst_bg_ratio_households_to_units\
        \             -0.0435     0.030    -1.464     0.143             \nst_bg_total_units\
        \                           -0.0005     0.035    -0.013     0.990        \
        \     \nst_density_jobs_90pct_plus                   0.0116     0.015    \
        \ 0.791     0.429             \nst_density_units_90pct_plus              \
        \    0.5791     0.009    62.062     0.000             \nst_pred_built_out_sf\
        \                        -0.1470     0.018    -8.090     0.000           \
        \  \nst_pred_rich_owned_antique                  -0.1196     0.055    -2.161\
        \     0.031             \nst_tracts_income_segment_1_hh               -0.0218\
        \     0.019    -1.130     0.258             \nst_tracts_income_segment_6_hh\
        \                0.0806     0.025     3.181     0.001             \nst_zones_density_units_ave_5_min_sov\
        \         0.1677     0.037     4.492     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.1421     0.178    -0.800     0.424             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.2850     0.046     6.155     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.4629     0.138     3.350     0.001             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.4942     0.113    -4.385     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.2139     0.173     1.240     0.215             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.4268     0.110     3.880     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.7765     0.189    -4.113     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.5917     0.096    -6.136     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.3567     0.204     1.746     0.081             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
