modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 3.084695036576827
    - 0.6200530330641544
    - 0.13427439161632285
    - -0.013417778358339067
    - -0.31790721316719606
    - 0.8029281262381278
    - 0.12205988990733803
    - 0.11662566449143491
    - 0.17416158160310527
    - -0.11873169025916246
    - 0.4807226701766327
    - -0.14036788101271117
    - -0.09246942058922816
    - -0.09144816470977482
    - 0.049385266627654835
    - 0.10669208795928609
    - -0.661694604848681
    - 0.015038534421771159
    - 0.3282697490390456
    - -0.31568316173584565
    - -0.38422565459722774
    - -0.1671867188348766
    - 0.13497001841885498
    - -0.06911255404037353
    - 0.9097956111953815
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          9,527\nModel:\
        \         Multinomial Logit   Df Residuals:              9,502\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.211\nTime:          \
        \            20:52   Pseudo R-bar-squ.:         0.210\nAIC:              \
        \    69,311.602   Log-Likelihood:      -34,630.801\nBIC:                 \
        \ 69,490.649   LL-Null:             -43,873.456\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    3.0847     0.011   284.866  \
        \   0.000             \nst_bg_mean_age_of_head                       0.6201\
        \     0.019    32.339     0.000             \nst_bg_mean_children        \
        \                  0.1343     0.015     9.107     0.000             \nst_bg_mean_year_built\
        \                       -0.0134     0.020    -0.685     0.494            \
        \ \nst_bg_median_value_13_acs                   -0.3179     0.025   -12.646\
        \     0.000             \nst_bg_prop_hh_rent                           0.8029\
        \     0.016    50.998     0.000             \nst_bg_prop_units_sf        \
        \                  0.1221     0.018     6.696     0.000             \nst_bg_ratio_households_to_units\
        \              0.1166     0.025     4.625     0.000             \nst_bg_total_units\
        \                            0.1742     0.028     6.247     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1187     0.017    -7.097\
        \     0.000             \nst_density_units_90pct_plus                  0.4807\
        \     0.009    54.644     0.000             \nst_pred_built_out_sf       \
        \                 -0.1404     0.013   -10.467     0.000             \nst_pred_rich_owned_antique\
        \                  -0.0925     0.042    -2.204     0.027             \nst_tracts_income_segment_1_hh\
        \               -0.0914     0.017    -5.323     0.000             \nst_tracts_income_segment_6_hh\
        \                0.0494     0.023     2.179     0.029             \nst_zones_density_units_ave_5_min_sov\
        \         0.1067     0.032     3.385     0.001             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.6617     0.140    -4.713     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.0150     0.038     0.397     0.691             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.3283     0.109     3.019     0.003             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.3157     0.091    -3.476     0.001             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.3842     0.140    -2.753     0.006             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.1672     0.098    -1.708     0.088             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.1350     0.155     0.874     0.382             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.0691     0.081    -0.857     0.392             \nst_zones_total_units_sum_10_min_sov\
        \          0.9098     0.159     5.723     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
