modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06095")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06095") '
    - ' (hh_type==3)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.1841075632519833
    - 0.5734175008474822
    - 0.1795746621861355
    - 0.24642025012849722
    - 0.07736124237807072
    - 1.0054450473994214
    - 0.36818139501852926
    - 0.5838302372291316
    - 0.11404536413024194
    - -0.23935991238140603
    - 0.08221125058227816
    - -0.04280872644041286
    - 0.010135373055898688
    - -0.26802453572142854
    - -0.5616922340179232
    - -0.08185497626812209
    - -0.013518976714662751
    - 0.7352751104948941
    - -1.2283071043612857
    - 0.9639710967317782
    - 0.4285160552731904
    - 0.9155715753805516
    - -2.29379026363244
    - -1.2223475537435549
    - 1.6989040740281331
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06095_blocks_own_2p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06095") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & (hh_type==3)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          4,784\nModel:\
        \         Multinomial Logit   Df Residuals:              4,759\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.186\nTime:          \
        \            18:44   Pseudo R-bar-squ.:         0.184\nAIC:              \
        \    35,935.496   Log-Likelihood:      -17,942.748\nBIC:                 \
        \ 36,097.322   LL-Null:             -22,031.134\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.1841     0.028    77.529  \
        \   0.000             \nst_bg_mean_age_of_head                       0.5734\
        \     0.026    21.678     0.000             \nst_bg_mean_children        \
        \                  0.1796     0.022     8.283     0.000             \nst_bg_mean_year_built\
        \                        0.2464     0.029     8.427     0.000            \
        \ \nst_bg_median_value_13_acs                    0.0774     0.056     1.377\
        \     0.169             \nst_bg_prop_hh_rent                           1.0054\
        \     0.040    25.268     0.000             \nst_bg_prop_units_sf        \
        \                  0.3682     0.032    11.354     0.000             \nst_bg_ratio_households_to_units\
        \              0.5838     0.040    14.658     0.000             \nst_bg_total_units\
        \                            0.1140     0.050     2.277     0.023        \
        \     \nst_density_jobs_90pct_plus                  -0.2394     0.050    -4.741\
        \     0.000             \nst_density_units_90pct_plus                  0.0822\
        \     0.025     3.231     0.001             \nst_pred_built_out_sf       \
        \                 -0.0428     0.028    -1.504     0.132             \nst_pred_rich_owned_antique\
        \                   0.0101     0.065     0.155     0.877             \nst_tracts_income_segment_1_hh\
        \               -0.2680     0.020   -13.334     0.000             \nst_tracts_income_segment_6_hh\
        \               -0.5617     0.093    -6.062     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.0819     0.047    -1.748     0.080             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.0135     0.234    -0.058     0.954             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.7353     0.086     8.558     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \               -1.2283     0.190    -6.474     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.9640     0.195     4.942     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.4285     0.251     1.706     0.088             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.9156     0.233     3.936     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -2.2938     0.345    -6.646     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -1.2223     0.228    -5.354     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          1.6989     0.382     4.450     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
