modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06041")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06041") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.3126858993104142
    - 0.3460388398584497
    - -0.10223411483545924
    - -0.1109326512079035
    - -0.16512311234953714
    - 0.959771172267192
    - 0.28039838688645646
    - 0.006829820936831142
    - 0.14013791450528765
    - -0.05255553278049234
    - 0.4223454504185952
    - -2.2771276064810166
    - -0.0984389526184827
    - -0.23378198174280385
    - 0.22781686441272092
    - 0.1296668882198985
    - -0.06034108169850847
    - 0.7109723288089353
    - 0.627967542363382
    - 0.14564187996638026
    - -0.3264113043466645
    - -0.004132934039964229
    - 0.1195925761069506
    - 0.4782622904528669
    - -1.7932575550018774
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06041_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06041") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          3,162\nModel:\
        \         Multinomial Logit   Df Residuals:              3,137\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.153\nTime:          \
        \            19:35   Pseudo R-bar-squ.:         0.152\nAIC:              \
        \    24,708.405   Log-Likelihood:      -12,329.202\nBIC:                 \
        \ 24,859.879   LL-Null:             -14,561.548\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.3127     0.026    90.412  \
        \   0.000             \nst_bg_mean_age_of_head                       0.3460\
        \     0.036     9.597     0.000             \nst_bg_mean_children        \
        \                 -0.1022     0.045    -2.258     0.024             \nst_bg_mean_year_built\
        \                       -0.1109     0.044    -2.531     0.011            \
        \ \nst_bg_median_value_13_acs                   -0.1651     0.034    -4.857\
        \     0.000             \nst_bg_prop_hh_rent                           0.9598\
        \     0.049    19.421     0.000             \nst_bg_prop_units_sf        \
        \                  0.2804     0.047     5.991     0.000             \nst_bg_ratio_households_to_units\
        \              0.0068     0.058     0.118     0.906             \nst_bg_total_units\
        \                            0.1401     0.051     2.722     0.006        \
        \     \nst_density_jobs_90pct_plus                  -0.0526     0.017    -3.089\
        \     0.002             \nst_density_units_90pct_plus                  0.4223\
        \     0.015    28.902     0.000             \nst_pred_built_out_sf       \
        \                 -2.2771     0.562    -4.053     0.000             \nst_pred_rich_owned_antique\
        \                  -0.0984     0.032    -3.037     0.002             \nst_tracts_income_segment_1_hh\
        \               -0.2338     0.041    -5.702     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2278     0.051     4.503     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1297     0.034     3.840     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.0603     0.310    -0.195     0.846             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.7110     0.133     5.365     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.6280     0.238     2.636     0.008             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.1456     0.194     0.752     0.452             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.3264     0.394    -0.829     0.407             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.0041     0.247    -0.017     0.987             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.1196     0.362     0.330     0.741             \nst_zones_total_jobs_sum_20_min_sov\
        \           0.4783     0.156     3.069     0.002             \nst_zones_total_units_sum_10_min_sov\
        \         -1.7933     0.351    -5.103     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
