modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==8)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.359230722577322
    - 0.44296114934251407
    - 0.15091381708211832
    - -0.07975043173071282
    - -0.052684362267027315
    - 0.5433983068805903
    - -0.12080206769116339
    - 0.24273614105340757
    - 0.29370732567028973
    - -0.003425533187502324
    - 0.646116624630188
    - 0.020696918740872147
    - -0.054373982612130826
    - 0.024962601033638163
    - -0.00898309937131125
    - -0.12488887499701373
    - -0.5904171510242295
    - -0.18059407770840266
    - 0.24240592779574233
    - 0.09494529249668972
    - -0.8457476458646493
    - -0.4249718702981682
    - 0.6343688089973968
    - -0.2094443251703096
    - 0.9748031349827574
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_rent_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==8)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          22,103\nModel:\
        \         Multinomial Logit   Df Residuals:              22,078\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.169\nTime:       \
        \               20:56   Pseudo R-bar-squ.:          0.169\nAIC:          \
        \       169,201.728   Log-Likelihood:       -84,575.864\nBIC:            \
        \     169,401.814   LL-Null:             -101,788.077\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.3592     0.006   363.300  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4430\
        \     0.011    39.192     0.000             \nst_bg_mean_children        \
        \                  0.1509     0.013    11.301     0.000             \nst_bg_mean_year_built\
        \                       -0.0798     0.011    -7.100     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.0527     0.012    -4.333\
        \     0.000             \nst_bg_prop_hh_rent                           0.5434\
        \     0.013    41.904     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1208     0.020    -5.961     0.000             \nst_bg_ratio_households_to_units\
        \              0.2427     0.026     9.248     0.000             \nst_bg_total_units\
        \                            0.2937     0.019    15.832     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.0034     0.006    -0.587\
        \     0.557             \nst_density_units_90pct_plus                  0.6461\
        \     0.007    90.968     0.000             \nst_pred_built_out_sf       \
        \                  0.0207     0.010     2.078     0.038             \nst_pred_rich_owned_antique\
        \                  -0.0544     0.017    -3.126     0.002             \nst_tracts_income_segment_1_hh\
        \                0.0250     0.008     2.993     0.003             \nst_tracts_income_segment_6_hh\
        \               -0.0090     0.009    -0.978     0.328             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1249     0.011   -11.434     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -0.5904     0.137    -4.320     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1806     0.030    -5.993     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.2424     0.071     3.422     0.001             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.0949     0.056     1.686     0.092             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.8457     0.116    -7.286     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.4250     0.062    -6.806     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.6344     0.118     5.357     0.000             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.2094     0.045    -4.693     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.9748     0.155     6.291     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
