modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06055")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06055") '
    - ' (hh_type==1)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.1113147454510064
    - 0.4846464043285545
    - 0.21374884591614723
    - -0.1554956489050047
    - -0.21147910888519908
    - 0.07689165380146747
    - 0.02349588991521505
    - 0.11854624805094685
    - -0.10082091224202787
    - -0.12702067611576573
    - -0.03575494692467497
    - 0.04791508489115389
    - 0.05968246637263383
    - 0.35812873847620397
    - -0.17993838756117683
    - 0.0037204043469813933
    - -1.875441138118438
    - 1.1659323434889153
    - 3.3888383001322966
    - -1.6593436851406709
    - 1.3695281296204895
    - 0.8548186373287405
    - 0.5268362819406955
    - -5.606714163291286
    - 1.5342431187591088
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum +  + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06055_blocks_own_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06055") & (zone_id
        == zone_id) & (zone_id == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & (hh_type==1)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            517\nModel:\
        \         Multinomial Logit   Df Residuals:                492\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.080\nTime:          \
        \            17:41   Pseudo R-bar-squ.:         0.069\nAIC:              \
        \     4,431.760   Log-Likelihood:       -2,190.880\nBIC:                 \
        \  4,537.961   LL-Null:              -2,380.873\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.1113     0.060    35.282  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4846\
        \     0.101     4.775     0.000             \nst_bg_mean_children        \
        \                  0.2137     0.076     2.803     0.005             \nst_bg_mean_year_built\
        \                       -0.1555     0.120    -1.292     0.197            \
        \ \nst_bg_median_value_13_acs                   -0.2115     0.089    -2.369\
        \     0.018             \nst_bg_prop_hh_rent                           0.0769\
        \     0.136     0.564     0.573             \nst_bg_prop_units_sf        \
        \                  0.0235     0.124     0.190     0.849             \nst_bg_ratio_households_to_units\
        \              0.1185     0.139     0.853     0.394             \nst_bg_total_units\
        \                           -0.1008     0.197    -0.511     0.609        \
        \     \nst_density_jobs_90pct_plus                  -0.1270     0.078    -1.638\
        \     0.101             \nst_density_units_90pct_plus                 -0.0358\
        \     0.063    -0.569     0.570             \nst_pred_built_out_sf       \
        \                  0.0479     0.035     1.381     0.167             \nst_pred_rich_owned_antique\
        \                   0.0597     0.118     0.506     0.613             \nst_tracts_income_segment_1_hh\
        \                0.3581     0.109     3.279     0.001             \nst_tracts_income_segment_6_hh\
        \               -0.1799     0.279    -0.644     0.520             \nst_zones_density_units_ave_5_min_sov\
        \         0.0037     0.112     0.033     0.973             \nst_zones_income_6_hh_sum_10_min_sov\
        \         -1.8754     1.463    -1.282     0.200             \nst_zones_jobs_0_sum_5_min_sov\
        \                1.1659     0.323     3.610     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                3.3888     0.918     3.693     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -1.6593     0.761    -2.181     0.029             \nst_zones_jobs_3_sum_5_min_sov\
        \                1.3695     1.480     0.925     0.355             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.8548     0.864     0.989     0.323             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.5268     1.670     0.316     0.752             \nst_zones_total_jobs_sum_20_min_sov\
        \          -5.6067     0.840    -6.675     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          1.5342     2.213     0.693     0.488             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
