modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06075")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06075") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 1.9110150001554056
    - 0.43366486334864784
    - -0.006190305132112278
    - -0.10419061074411888
    - -0.055311351215899286
    - -0.23434823747449787
    - -0.02202752206314026
    - 0.2202252386316249
    - 0.12728407548189213
    - -0.12048788856360848
    - 0.42200699080416215
    - 0.0199555785790696
    - 0.048433408603206066
    - -0.027153562770034015
    - 0.11181936924936867
    - -0.10186905282754713
    - 0.5056850299726637
    - -0.1716042668439697
    - 0.4461862120201305
    - -0.4726531944630792
    - 0.22102868925630723
    - -0.2910098181629811
    - -0.13640401750827205
    - -0.10725712668693936
    - 0.01664944102435062
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06075_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06075") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          34,519\nModel:\
        \         Multinomial Logit   Df Residuals:              34,494\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.090\nTime:       \
        \               19:12   Pseudo R-bar-squ.:          0.089\nAIC:          \
        \       289,504.033   Log-Likelihood:      -144,727.016\nBIC:            \
        \     289,715.264   LL-Null:             -158,965.870\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    1.9110     0.006   342.847  \
        \   0.000             \nst_bg_mean_age_of_head                       0.4337\
        \     0.013    34.570     0.000             \nst_bg_mean_children        \
        \                 -0.0062     0.011    -0.580     0.562             \nst_bg_mean_year_built\
        \                       -0.1042     0.012    -8.444     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.0553     0.014    -4.055\
        \     0.000             \nst_bg_prop_hh_rent                          -0.2343\
        \     0.012   -19.913     0.000             \nst_bg_prop_units_sf        \
        \                 -0.0220     0.016    -1.401     0.161             \nst_bg_ratio_households_to_units\
        \              0.2202     0.023     9.666     0.000             \nst_bg_total_units\
        \                            0.1273     0.020     6.477     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.1205     0.006   -19.260\
        \     0.000             \nst_density_units_90pct_plus                  0.4220\
        \     0.004    96.271     0.000             \nst_pred_built_out_sf       \
        \                  0.0200     0.004     5.604     0.000             \nst_pred_rich_owned_antique\
        \                   0.0484     0.003    14.255     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.0272     0.011    -2.541     0.011             \nst_tracts_income_segment_6_hh\
        \                0.1118     0.009    12.903     0.000             \nst_zones_density_units_ave_5_min_sov\
        \        -0.1019     0.009   -11.005     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.5057     0.096     5.254     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \               -0.1716     0.022    -7.704     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.4462     0.047     9.465     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.4727     0.046   -10.264     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \                0.2210     0.087     2.526     0.012             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.2910     0.051    -5.740     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.1364     0.090    -1.520     0.129             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.1073     0.040    -2.682     0.007             \nst_zones_total_units_sum_10_min_sov\
        \          0.0166     0.114     0.146     0.884             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
