modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_residential_units
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: households
  constrained_choices: true
  fitted_parameters:
  - 0.01475307997316122
  - -0.16985183954238892
  - 0.26134493947029114
  - -0.24533231556415558
  - 0.17502497136592865
  - 0.3760521113872528
  - 0.09945087134838104
  - 0.26044830679893494
  - -0.006334724836051464
  - 0.3739805817604065
  - -0.00014367193216457963
  - -0.1068982258439064
  - 0.14756815135478973
  - -0.03720264881849289
  - 0.10579120367765427
  - 1.5842108726501465
  - 0.21164573729038239
  - -4.167385101318359
  - 0.34835684299468994
  - -0.5647486448287964
  - -0.7058216333389282
  - 4.8228020668029785
  - 0.20815816521644592
  - -1.4974056482315063
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: hlcm_06081_blocks_pf
  out_alt_filters: (vacant_residential_units > 0) & (county_id == "06081")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06081")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
