modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06013")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06013") '
    - ' (hh_type==4)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.6878648555728977
    - 0.8236319449570039
    - 0.13126366383790433
    - 0.14206097265901965
    - -0.333060185221526
    - 0.29122457760951553
    - 0.2908672524564035
    - 0.2198318259043755
    - 0.042886450504433224
    - -0.3107368491374306
    - 0.07777103136235335
    - -0.07913068914934786
    - 0.038486847719494524
    - -0.17236218274956275
    - 0.1532974055159747
    - 0.10955760399014697
    - 0.2163964621168788
    - 0.14826649535844022
    - 0.16344252305333798
    - -0.25154083145757217
    - -0.08500348356819133
    - -0.26179710176214605
    - -0.013494714578910705
    - -0.42191111178041274
    - 0.3704553109616809
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06013_blocks_own_2p_55plus_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06013") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06013") & (hh_type==4)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \       \n====================================================================\n\
        Dep. Var.:                chosen   No. Observations:          49,305\nModel:\
        \         Multinomial Logit   Df Residuals:              49,280\nMethod: \
        \      Maximum Likelihood   Df Model:                      25\nDate:     \
        \            2023-06-29   Pseudo R-squ.:              0.101\nTime:       \
        \               18:58   Pseudo R-bar-squ.:          0.100\nAIC:          \
        \       408,482.897   Log-Likelihood:      -204,216.449\nBIC:            \
        \     408,703.042   LL-Null:             -227,057.916\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.6879     0.005   540.885  \
        \   0.000             \nst_bg_mean_age_of_head                       0.8236\
        \     0.008   106.763     0.000             \nst_bg_mean_children        \
        \                  0.1313     0.007    18.038     0.000             \nst_bg_mean_year_built\
        \                        0.1421     0.008    16.958     0.000            \
        \ \nst_bg_median_value_13_acs                   -0.3331     0.009   -35.652\
        \     0.000             \nst_bg_prop_hh_rent                           0.2912\
        \     0.009    31.588     0.000             \nst_bg_prop_units_sf        \
        \                  0.2909     0.010    30.213     0.000             \nst_bg_ratio_households_to_units\
        \              0.2198     0.011    19.310     0.000             \nst_bg_total_units\
        \                            0.0429     0.011     3.966     0.000        \
        \     \nst_density_jobs_90pct_plus                  -0.3107     0.012   -26.045\
        \     0.000             \nst_density_units_90pct_plus                  0.0778\
        \     0.008    10.070     0.000             \nst_pred_built_out_sf       \
        \                 -0.0791     0.005   -15.245     0.000             \nst_pred_rich_owned_antique\
        \                   0.0385     0.007     5.563     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.1724     0.007   -24.140     0.000             \nst_tracts_income_segment_6_hh\
        \                0.1533     0.008    20.261     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1096     0.014     8.112     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.2164     0.061     3.523     0.000             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.1483     0.018     8.345     0.000             \nst_zones_jobs_1_sum_5_min_sov\
        \                0.1634     0.045     3.663     0.000             \nst_zones_jobs_2_sum_5_min_sov\
        \               -0.2515     0.040    -6.258     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.0850     0.062    -1.366     0.172             \nst_zones_jobs_4_sum_5_min_sov\
        \               -0.2618     0.040    -6.494     0.000             \nst_zones_jobs_5_sum_5_min_sov\
        \               -0.0135     0.067    -0.200     0.841             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.4219     0.037   -11.456     0.000             \nst_zones_total_units_sum_10_min_sov\
        \          0.3705     0.069     5.348     0.000             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
