modelmanager_version: 0.2.dev9

saved_object:
    alt_capacity: vacant_residential_units
    alt_filters:
    - (county_id == "06085")
    alt_sample_size: 100
    alternatives: blocks
    choice_column: block_id
    chooser_filters:
    - ' (lcm_county_id == "06085") '
    - ' (hh_type==5)'
    chooser_sample_size: null
    chooser_size: null
    choosers: households
    constrained_choices: true
    fitted_parameters:
    - 2.5605035647089793
    - -0.022949434680314924
    - -0.4279836606308109
    - -0.24734020810385202
    - 0.02208863415736857
    - 0.973752176489632
    - -0.18309471948410996
    - 0.40476144522501256
    - 0.006506688376621458
    - -0.2429385086714106
    - 0.6273527842499808
    - -0.031710466289420834
    - -0.13491584472282972
    - -0.25344852166763343
    - 0.20195633570951385
    - 0.1602362328965183
    - 0.16782858255316804
    - 0.05131585352371754
    - -0.2283932561149592
    - 0.43837773494873816
    - -0.5918797647617552
    - 0.15429231004262656
    - 0.0689328931671602
    - -0.16614871805446244
    - 0.04856797085729915
    max_iter: null
    mct_intx_ops:
        extra_alts_cols:
        - zone_id
        successive_merges:
        -   mct_cols:
            - household_id
            - zone_id
            - mct_index
            on_cols:
            - household_id
            right_cols:
            - household_id
            - mandatory_work_zone_id
            - mandatory_school_zone_id
            - mandatory_school_dummy
            - mandatory_work_dummy
            - mandatory_activity_dummy
            right_table: persons
        -   how: left
            left_on:
            - zone_id
            - mandatory_work_zone_id
            right_index: true
            right_table: travel_data
        -   how: left
            left_on:
            - zone_id
            - mandatory_school_zone_id
            right_index: true
            right_table: travel_data
            suffixes:
            - _work
            - _school
        aggregations:
            logsum_school: max
            logsum_work: max
            mandatory_activity_dummy: max
            mandatory_school_dummy: max
            mandatory_work_dummy: max
        rename_cols:
            logsum_school: max_school_logsum
            logsum_work: max_work_logsum
        sequential_eval_ops:
        -   expr: 1 - mandatory_work_dummy
            name: no_work
        -   engine: python
            expr: max_work_logsum.fillna(0)
            name: work_nan_fill
        -   engine: python
            expr: max_school_logsum.fillna(0)
            name: school_nan_fill
        -   expr: (work_nan_fill * mandatory_work_dummy) + (no_work * school_nan_fill
                * mandatory_school_dummy)
            name: mandatory_logsum
    model_expression: mandatory_activity_dummy:mandatory_logsum + st_bg_mean_age_of_head
        + st_bg_mean_children + st_bg_mean_year_built + st_bg_median_value_13_acs
        + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
        + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
        + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
        + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
        + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
        + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
        + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov
        - 1
    name: hlcm_06085_blocks_rent_1p_54less_pf
    out_alt_filters: (vacant_residential_units > 0) & (county_id == "06085") & (zone_id
        == zone_id) & (zone_id == zone_id)
    out_alternatives: null
    out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06085") & (hh_type==5)
    out_choosers: null
    out_column: block_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:         10,198\nModel:\
        \         Multinomial Logit   Df Residuals:             10,173\nMethod:  \
        \     Maximum Likelihood   Df Model:                     25\nDate:       \
        \          2023-06-29   Pseudo R-squ.:             0.343\nTime:          \
        \            19:44   Pseudo R-bar-squ.:         0.342\nAIC:              \
        \    61,760.932   Log-Likelihood:      -30,855.466\nBIC:                 \
        \ 61,941.680   LL-Null:             -46,963.526\n==============================================================================================\n\
        \                                               coef   std err         z \
        \    P>|z|   Conf. Int.\n----------------------------------------------------------------------------------------------\n\
        mandatory_activity_dummy:mandatory_logsum    2.5605     0.014   182.367  \
        \   0.000             \nst_bg_mean_age_of_head                      -0.0229\
        \     0.016    -1.440     0.150             \nst_bg_mean_children        \
        \                 -0.4280     0.016   -25.943     0.000             \nst_bg_mean_year_built\
        \                       -0.2473     0.022   -11.066     0.000            \
        \ \nst_bg_median_value_13_acs                    0.0221     0.017     1.304\
        \     0.192             \nst_bg_prop_hh_rent                           0.9738\
        \     0.021    46.450     0.000             \nst_bg_prop_units_sf        \
        \                 -0.1831     0.022    -8.264     0.000             \nst_bg_ratio_households_to_units\
        \              0.4048     0.040    10.014     0.000             \nst_bg_total_units\
        \                            0.0065     0.025     0.259     0.796        \
        \     \nst_density_jobs_90pct_plus                  -0.2429     0.012   -20.955\
        \     0.000             \nst_density_units_90pct_plus                  0.6274\
        \     0.007    85.949     0.000             \nst_pred_built_out_sf       \
        \                 -0.0317     0.025    -1.244     0.213             \nst_pred_rich_owned_antique\
        \                  -0.1349     0.037    -3.669     0.000             \nst_tracts_income_segment_1_hh\
        \               -0.2534     0.025   -10.203     0.000             \nst_tracts_income_segment_6_hh\
        \                0.2020     0.016    12.405     0.000             \nst_zones_density_units_ave_5_min_sov\
        \         0.1602     0.042     3.789     0.000             \nst_zones_income_6_hh_sum_10_min_sov\
        \          0.1678     0.141     1.187     0.235             \nst_zones_jobs_0_sum_5_min_sov\
        \                0.0513     0.042     1.215     0.225             \nst_zones_jobs_1_sum_5_min_sov\
        \               -0.2284     0.078    -2.938     0.003             \nst_zones_jobs_2_sum_5_min_sov\
        \                0.4384     0.098     4.489     0.000             \nst_zones_jobs_3_sum_5_min_sov\
        \               -0.5919     0.151    -3.919     0.000             \nst_zones_jobs_4_sum_5_min_sov\
        \                0.1543     0.136     1.138     0.255             \nst_zones_jobs_5_sum_5_min_sov\
        \                0.0689     0.191     0.361     0.718             \nst_zones_total_jobs_sum_20_min_sov\
        \          -0.1661     0.082    -2.035     0.042             \nst_zones_total_units_sum_10_min_sov\
        \          0.0486     0.137     0.356     0.722             \n=============================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.2.dev9
