modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - -0.30463793873786926
  - -0.7939255237579346
  - 0.29569700360298157
  - 0.09705852717161179
  - -0.3206605315208435
  - 1.3265959024429321
  - 0.3680708110332489
  - 0.3648894727230072
  - 0.785506010055542
  - 0.6340000629425049
  - -0.001896078698337078
  - -0.5290722250938416
  - 0.2543119192123413
  - -0.18856896460056305
  - 0.9448174238204956
  - 0.24186591804027557
  - -0.2934858798980713
  - -0.25247958302497864
  - -0.34538787603378296
  - -0.17897093296051025
  - 0.054276734590530396
  - -0.07554890960454941
  - 0.5076434016227722
  - 0.08781825006008148
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06055_blocks_sf_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055") & ((building_type=="sf_own")
    | (building_type=="sf_rent"))
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
