modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.38663357496261597
  - 0.3186163902282715
  - 0.021804850548505783
  - 0.0003523019258864224
  - 0.31076741218566895
  - 0.05123591795563698
  - 0.546113908290863
  - -0.011637335643172264
  - -0.6102991104125977
  - 1.681349754333496
  - -0.2538972795009613
  - -0.4146077334880829
  - -0.1669255793094635
  - 0.21370543539524078
  - -0.22687582671642303
  - 0.05241939797997475
  - -0.9639381766319275
  - 1.025822639465332
  - -0.7652776837348938
  - 0.989367663860321
  - -0.1482423096895218
  - -0.7865402698516846
  - 0.0009891798254102468
  - 0.5469828844070435
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06095_blocks_mf_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06095")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095") & ((building_type=="mf_own")
    | (building_type=="mf_rent"))
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
