modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.4027242660522461
  - 0.3067723214626312
  - 0.021897394210100174
  - 0.18132254481315613
  - 0.3375750482082367
  - 0.5611141920089722
  - 0.158055379986763
  - 0.5944396257400513
  - 0.6508830785751343
  - -0.7801144123077393
  - -0.008675871416926384
  - -0.6100315451622009
  - 0.41637054085731506
  - 0.5916916728019714
  - -0.40791380405426025
  - 0.1592589169740677
  - -0.2443285435438156
  - -0.1135513186454773
  - -0.1973964422941208
  - -0.06620548665523529
  - 0.05441473796963692
  - -0.05988987907767296
  - 0.4884418249130249
  - 0.09611481428146362
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06055_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06055")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06055")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
