modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - -0.5345557928085327
  - -0.3804115056991577
  - 0.3540225028991699
  - 0.0014430024893954396
  - -0.4605523645877838
  - 0.6922023296356201
  - -0.23074640333652496
  - 0.10765562951564789
  - -0.015932399779558182
  - 0.511863648891449
  - -0.9898125529289246
  - 0.1889379322528839
  - 0.511935830116272
  - -0.14190761744976044
  - 0.08511780202388763
  - 1.4858607053756714
  - 5.97920560836792
  - -1.936875343322754
  - -3.40824031829834
  - -2.39704966545105
  - -1.8396472930908203
  - -5.059300422668457
  - 0.004754765424877405
  - -0.1254369169473648
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06041_blocks_sf_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06041")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06041") & ((building_type=="sf_own")
    | (building_type=="sf_rent"))
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
