modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.28193992376327515
  - 0.31637638807296753
  - 0.29501795768737793
  - 0.001547059859149158
  - 0.3775411546230316
  - 0.6680002212524414
  - 0.1486644446849823
  - -0.41510629653930664
  - 0.24210265278816223
  - 0.7092493176460266
  - -0.8993111252784729
  - 0.26711583137512207
  - 0.17205339670181274
  - -0.3680838644504547
  - -0.15054696798324585
  - 0.16487210988998413
  - 0.02329593524336815
  - 0.41566914319992065
  - -0.23837384581565857
  - -0.04397246986627579
  - -0.6510491967201233
  - -0.09907610714435577
  - 0.0003221556544303894
  - 0.3647204339504242
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06097_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06097")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06097")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
