modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.07236450910568237
  - 0.061328060925006866
  - 0.12170152366161346
  - 0.0021562036126852036
  - -0.008769667707383633
  - -0.009421220049262047
  - 0.24202995002269745
  - -0.03495388105511665
  - 0.021464670076966286
  - 0.6294645667076111
  - -0.011075383052229881
  - 0.14891353249549866
  - 0.0579032227396965
  - -0.3143763542175293
  - -0.644748330116272
  - 0.8788248896598816
  - -0.15128609538078308
  - -2.806764602661133
  - 0.5164417028427124
  - -0.6582116484642029
  - 3.4312350749969482
  - 0.17244602739810944
  - 0.4082081615924835
  - -0.4121396243572235
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06001_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06001")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06001")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
