modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - -0.11217059940099716
  - 0.11111605167388916
  - 0.20161664485931396
  - 0.001518321456387639
  - -0.05152362957596779
  - -0.1438518762588501
  - -0.13625182211399078
  - 0.09050099551677704
  - 0.04885394498705864
  - 0.8917796015739441
  - -0.028822198510169983
  - 0.14003905653953552
  - 0.07024189084768295
  - -0.029064523056149483
  - -0.11888236552476883
  - 0.4538218379020691
  - -0.2473393827676773
  - -0.4755159616470337
  - 0.033654846251010895
  - 0.453233540058136
  - -0.2658420503139496
  - 0.6752161383628845
  - 0.0024394546635448933
  - -0.4567248225212097
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06075_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06075")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06075")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
