modelmanager_version: 0.2.dev9
saved_object:
  alt_capacity: vacant_du_spaces
  alt_filters: null
  alt_sample_size: 100
  alternatives: blocks
  choice_column: block_id
  chooser_filters: null
  chooser_sample_size: null
  chooser_size: null
  choosers: residential_units
  constrained_choices: true
  fitted_parameters:
  - 0.08341816812753677
  - 0.026219598948955536
  - 0.0167938731610775
  - 0.00036113476380705833
  - 0.11768117547035217
  - 0.5088064074516296
  - 0.9772908091545105
  - 0.22878523170948029
  - -0.32784825563430786
  - 1.0384355783462524
  - -0.5758351683616638
  - 0.38892731070518494
  - -0.0389833077788353
  - -1.1503524780273438
  - 0.642939031124115
  - -0.14475888013839722
  - -0.4639425277709961
  - 0.16286732256412506
  - -1.5092607736587524
  - 0.43712055683135986
  - -0.341778963804245
  - -0.31176459789276123
  - 0.0007535199401900172
  - 0.6900661587715149
  max_iter: null
  model_expression: st_bg_mean_age_of_head + st_bg_mean_children + st_bg_mean_year_built
    + st_bg_median_value_13_acs + st_bg_prop_hh_rent + st_bg_prop_units_sf + st_bg_ratio_households_to_units
    + st_bg_total_units + st_density_jobs_90pct_plus + st_density_units_90pct_plus
    + st_pred_built_out_sf + st_pred_rich_owned_antique + st_tracts_income_segment_1_hh
    + st_tracts_income_segment_6_hh + st_zones_density_units_ave_5_min_sov + st_zones_income_6_hh_sum_10_min_sov
    + st_zones_jobs_0_sum_5_min_sov + st_zones_jobs_1_sum_5_min_sov + st_zones_jobs_2_sum_5_min_sov
    + st_zones_jobs_3_sum_5_min_sov + st_zones_jobs_4_sum_5_min_sov + st_zones_jobs_5_sum_5_min_sov
    + st_zones_total_jobs_sum_20_min_sov + st_zones_total_units_sum_10_min_sov - 1
  name: rdplcm_06095_blocks_pf
  out_alt_filters: (vacant_du_spaces > 0) & (county_id == "06095")
  out_alternatives: null
  out_chooser_filters: (block_id == "-1") & (lcm_county_id == "06095")
  out_choosers: null
  out_column: block_id
  summary_table: null
  tags: []
  template: LargeMultinomialLogitStep
  template_version: 0.2.dev9
