modelmanager_version: 0.2.dev9

saved_object:
    filters: null
    fitted_parameters:
    - -3.2543275
    - 0.9425
    - 0.83806
    model_expression: birth ~ hh_birth_agebin1 + hh_birth_agebin2 + 1
    name: household_birth_model
    out_column: null
    out_filters: null
    out_tables: null
    out_transform: null
    out_value_false: 0
    out_value_true: 1
    tables: households
    summary_table: null
    tags: []
    template: BinaryLogitStep
    template_version: 0.2.dev9