modelmanager_version: 0.2.dev9
saved_object:
  filters: (worker == 0) & (age >= 18)
  fitted_parameters:
    - -0.0185182
    - 0.3578597
    - 0.8037832
    - 1.2053345
    - 2.3996862
    - 4.3787252
    - 0.2860831
    - -0.4146881
    - -0.7963939
  model_expression: stay_out ~ agebin1_labor + agebin2_labor + agebin3_labor + agebin4_labor + agebin5_labor + gender2 + edubin2 + edubin3 + 1
  name: enter_labor_force_model
  out_column: null
  out_filters:
    - (worker == 0) & (age >= 18)
  out_tables: persons
  out_transform: null
  out_value_false: 0
  out_value_true: 1
  summary_table: null
  tables: persons
  tags: []
  template: BinaryLogitStep
  template_version: 0.2.dev9
