modelmanager_version: 0.2.dev9
saved_object:
    filters: null
    fitted_parameters:
    - -10.062937
    - 0.08047558
    - -0.98160255 
    - 1.1442612
    - 1.2404861
    - -0.04225827 
    - -0.31910235
    - -0.19940826
    - 0.8482214
    - 0.6148795
    - 0.60858643
    model_expression: dead ~ age + gender2 + employbin2 + employbin3
        + edubin2 + edubin3 + race1 + marital2 + marital3 + marital4 + 1
    name: mortality_model
    out_column: null
    out_filters: null
    out_tables: null
    out_transform: null
    out_value_false: 0
    out_value_true: 1
    tables: persons
    summary_table: null
    tags: []
    template: BinaryLogitStep
    template_version: 0.2.dev9